### PR TITLE
Update counter of UEFI configuration tables.

### PR DESCRIPTION
**Pull request by assafcarlsbad**
During runtime, UEFI code might install additional configuration tables via [`InstallConfigurationTable`](https://edk2-docs.gitbook.io/edk-ii-uefi-driver-writer-s-guide/5_uefi_services/readme.2/5210_installconfigurationtable) or via [`SmmInstallConfigurationTable`](https://github.com/tianocore/edk2/blob/master/MdePkg/Include/Pi/PiSmmCis.h). Until now, the counter associated with each configuration table was static and thus new entries would remain hidden from client code. This PR remedies this deficiency by simply incrementing the counter upon successful installation of a new configuration table entry.

@elicn 

### Which kind of PR do you create?

- [x] This PR only contains minor fixes.
- [ ] This PR contains major feature update.
- [ ] This PR introduces a new function/api for Qiling Framework.

### Coding convention?

- [x] The new code conforms to Qiling Framework naming convention.
- [x] The imports are arranged properly.
- [x] Essential comments are added.
- [ ] The reference of the new code is pointed out.

### Extra tests?

- [ ] No extra tests are needed for this PR.
- [ ] I have added enough tests for this PR.
- [x] Tests will be added after some discussion and review.

### Changelog?

- [x] This PR doesn't need to update Changelog.
- [ ] Changelog will be updated after some proper review.
- [ ] Changelog has been updated in my PR.

### Target branch?

- [x] The target branch is dev branch.

### One last thing

- [x] I have read the [contribution guide](https://docs.qiling.io/en/latest/contribution/)

-----

### CODE REVIEW

**Comment by elicn** [comment]
Thanks, I was too lazy to implement that (:

Note that the conf install methods are used also for updating existing entries. Increasing the counter by one in these cases would result in a wrong number. Perhaps setting it to `len(ql.loader.efi_conf_table_array)` would be better.

I would prefer the update to be done on the install methods, where they belong.
Could you please elaborate on when conf tables might be installed before `gST` / `gSmst` are initialized..? (any specific test case?)
I'll try to look into it.

**Comment by assafcarlsbad** [comment]
In `st.py` we call `install_configuration_table` twice before initializing the memory pointed to be `gST`:

```
install_configuration_table(ql, "HOB_LIST", None)
install_configuration_table(ql, "DXE_SERVICE_TABLE", gDS)

instance = EFI_SYSTEM_TABLE()
instance.RuntimeServices = gRT
instance.BootServices = gBS
instance.NumberOfTableEntries = len(confs)	# HOB_LIST and DXE_SERVICES
instance.ConfigurationTable = cfg

instance.saveTo(ql, gST)
```

**Comment by elicn** [comment]
Yes, that's a good idea..

**Comment by xwings** [comment]
> maybe we can reverse the order of operations (first initialize the `EFI_SYSTEM_TABLE`, then install the configuration tables). WDYT?

Do you want to do it in this PR or the next one ?

**Review by elicn — APPROVED** [review]

**Comment by xwings** [comment]
Cool.

merged.

**Pull request merged**
