### PR TITLE
Refactor MCU module

### PR DESCRIPTION
**Pull request by cla7aye15I4nd**
- Move MCU from ARCH to OS, `os.run` replaced `arch.run`.
- Add FRDM-K64F, Arduino Due board support.
- Support save/restore peripheral's context.
- Move bitband and remap into peripheral.
- Add `fast_mode` in MCU emulation.

### CODE REVIEW

**Review by xwings — APPROVED** [review]

**Review by xwings — APPROVED** [review]

**Review by kabeor — APPROVED** [review]

**Comment by xwings** [comment]
@elicn any comments ?

**Comment by elicn** [comment]
> @elicn any comments ?

That is... going to take me some time to review.
I'll try to do it that over the weekend.

**Review by elicn — APPROVED** [review]
I didn't have much to contribute here except as few petty code quality / styling comments.
Great work!

**Comment by cla7aye15I4nd** [comment]
The multitasking extension is currently only for the MCU, we will improve it in the future

**Pull request merged**
