### PR TITLE
Fix socket_type confuse

### PR DESCRIPTION
**Pull request by dark-lbp**
Fix socket_type confuse, we should convert socket type, level and opt to host platform based value.

### Which kind of PR do you create?

- [x] This PR only contains minor fixes.
- [ ] This PR contains major feature update.
- [ ] This PR introduces a new function/api for Qiling Framework.

### Coding convention?

- [x] The new code conforms to Qiling Framework naming convention.
- [x] The imports are arranged properly.
- [x] Essential comments are added.
- [x] The reference of the new code is pointed out.

### Extra tests?

- [ ] No extra tests are needed for this PR.
- [ ] I have added enough tests for this PR.
- [x] Tests will be added after some discussion and review.

### Changelog?

- [ ] This PR doesn't need to update Changelog.
- [x] Changelog will be updated after some proper review.
- [ ] Changelog has been updated in my PR.

### Target branch?

- [x] The target branch is dev branch.

### One last thing

- [x] I have read the [contribution guide](https://docs.qiling.io/en/latest/contribution/)

-----

### CODE REVIEW

**Comment by dark-lbp** [comment]
Can't reproduce this CI fault with my local environment, It's weird.

```python
======================================================================
ERROR: test_elf_linux_execve_x8664 (__main__.ELFTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/qiling/utils.py", line 239, in ql_get_module_function
    imp_module = importlib.import_module(module_name)
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load
  File "<frozen importlib._bootstrap>", line 158, in __enter__
  File "<frozen importlib._bootstrap>", line 110, in acquire
KeyError: 140518416910144

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/qiling/qiling/tests/./test_elf_multithread.py", line 23, in test_elf_linux_execve_x8664
    ql.run()
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/qiling/core.py", line 755, in run
    self.os.run()
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/qiling/os/linux/linux.py", line 133, in run
    self.ql.emu_start(self.ql.loader.entry_point, entry_address, self.ql.timeout)
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/qiling/core.py", line 899, in emu_start
    raise self._internal_exception
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/qiling/utils.py", line 158, in wrapper
    return func(*args, **kw)
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/qiling/core_hooks.py", line 81, in _hook_insn_cb
    ret = h.call(ql, *args[ : -1])
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/qiling/core_hooks_types.py", line 23, in call
    return self.callback(ql, *args)
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/qiling/os/linux/linux.py", line 94, in hook_syscall
    return self.load_syscall()
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/qiling/os/posix/posix.py", line 165, in load_syscall
    _posix_syscall = ql_get_module_function(f"qiling.os.posix", "syscall")
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/qiling/utils.py", line 243, in ql_get_module_function
    raise QlErrorModuleNotFound(f'Unable to import module {module_name}')
qiling.exception.QlErrorModuleNotFound: Unable to import module qiling.os.posix
[=] [Thread 2805]	close(fd = 0x3) = 0x0
```

**Comment by xwings** [comment]
did u try with python 3.9.5 ?

**Comment by dark-lbp** [comment]
> did u try with python 3.9.5 ?

Yeah, ubuntu 18.04 with python 3.9.5, Download from "https://github.com/actions/python-versions/releases/download/3.9.5-109482/python-3.9.5-linux-18.04-x64.tar.gz"

**Comment by xwings** [comment]
Interesting. I tried and seems ok. Funny issue.

**Comment by xwings** [comment]
I upgraded the python version. Will you able to sync the base code and try again ?

**Comment by dark-lbp** [comment]
> I upgraded the python version. Will you able to sync the base code and try again ?

Sure, opened new PR #881

**Pull request closed without merging**
