### PR TITLE
add syscall _llseek

### PR DESCRIPTION
**Pull request by ucgJhe**
Try to emulate binary compiled from mipsel-linux-gnu-gcc in Ubuntu and complete the syscall.

P.S. basically it's a wrapper for lseek but for larger size.

### CODE REVIEW

**Comment by xwings** [comment]
Hi,

Please check the log and code seems to be broken.

Can you please fix it ?

**Comment by ucgJhe** [comment]
yep sure.

**Comment by xwings** [comment]
Hi,

a bit more minor change
white lines between functions is two rows not 3. python recomended way.

**Comment by xwings** [comment]
hi, 

you also need to map the code to the arch you need.
if you test agiants mips, 

you need to ass the syscall to  qiling/os/linux/mips32el_syscall.py and match the syscall number

syscall can be refer from here:

https://w3challs.com/syscalls/?arch=mips_o32

**Comment by xwings** [comment]
thanks !

**Pull request merged**
