### PR TITLE
Implement stateful SimpleStringBuffer

### PR DESCRIPTION
**Pull request by wtdcode**
### Which kind of PR do you create?

- [x] This PR only contains minor fixes.
- [ ] This PR contains major feature update.
- [ ] This PR introduces a new function/api for Qiling Framework.

### Coding convention?

- [x] The new code conforms to Qiling Framework naming convention.
- [x] The imports are arranged properly.
- [x] Essential comments are added.
- [x] The reference of the new code is pointed out.

### Extra tests?

- [x] No extra tests are needed for this PR.
- [ ] I have added enough tests for this PR.
- [ ] Tests will be added after some discussion and review.

### Changelog?

- [x] This PR doesn't need to update Changelog.
- [ ] Changelog will be updated after some proper review.
- [ ] Changelog has been updated in my PR.

### Target branch?

- [x] The target branch is dev branch.

### One last thing

- [x] I have read the [contribution guide](https://docs.qiling.io/en/latest/contribution/)

-----

### CODE REVIEW

**Comment by elicn** [comment]
@wtdcode, can you give a little bit of context around that fix..?

As stated on the `SimpleStringBuffer` docstring, it is a FIFO stream; being able to seek is a _random access_ feature which breaks the FIFO property. That also requires storing the entire content of the stream throughout its lifetime (i.e. reading part of it doesn't let you get rid of that part), which becomes problematic when using it for `stdout` that may potentially yield tons of output.

Would you prefer to create a `BufferedStream` class that supports `seek`, just like `io.BufferedRandom` ?

**Comment by wtdcode** [comment]
> @wtdcode, can you give a little bit of context around that fix..?
> 
> As stated on the `SimpleStringBuffer` docstring, it is a FIFO stream; being able to seek is a _random access_ feature which breaks the FIFO property. That also requires storing the entire content of the stream throughout its lifetime (i.e. reading part of it doesn't let you get rid of that part), which becomes problematic when using it for `stdout` that may potentially yield tons of output.
> 
> Would you prefer to create a `BufferedStream` class that supports `seek`, just like `io.BufferedRandom` ?

Yes, you are right. I would create another subclass.

**Comment by elicn** [comment]
> Yes, you are right. I would create another subclass.

Consider adding:
```python
def seekable(self) -> bool:
    return True
```

To indicate it is a seek-able stream.

**Review by kabeor — APPROVED** [review]

**Comment by elicn** [comment]
Not sure, but I think @wtdcode wanted to create another PR instead of this one.

**Comment by wtdcode** [comment]
Yes, indeed
________________________________

**Comment by wtdcode** [comment]
Closed due to #1071

**Pull request closed without merging**
