### PR TITLE
OS improvements

### PR DESCRIPTION
**Pull request by elicn**
Some improvements to the OS module:
- New and improved function arguments handling
  - Selects between `amd64`, `cdecl` and `ms` calling conventions instead of just 32 vs 64 bits
  - Uses a unified generic handling instead of re-selecting appropriate handling every single time
  - Supports up to 8 function call arguments in each cc
- Code cleanup and tidy-up
- Documentation

Note that not all the OS methods are triggered in the current test suite. This may need a more aggressive testing

### Which kind of PR do you create?

- [x] This PR only contains minor fixes.
- [ ] This PR contains major feature update.
- [ ] This PR introduces a new function/api for Qiling Framework.

### Coding convention?

- [x] The new code conforms to Qiling Framework naming convention.
- [x] The imports are arranged properly.
- [x] Essential comments are added.
- [ ] The reference of the new code is pointed out.

### Extra tests?

- [ ] No extra tests are needed for this PR.
- [ ] I have added enough tests for this PR.
- [x] Tests will be added after some discussion and review.

### Changelog?

- [x] This PR doesn't need to update Changelog.
- [ ] Changelog will be updated after some proper review.
- [ ] Changelog has been updated in my PR.

### Target branch?

- [x] The target branch is dev branch.

### One last thing

- [x] I have read the [contribution guide](https://docs.qiling.io/en/latest/contribution/)

-----

### CODE REVIEW

**Comment by xwings** [comment]
Ah, I did not see this PR. and I updated the header.

Can you please update your code?

**Comment by elicn** [comment]
Rebased

**Comment by elicn** [comment]
It worth mentioning that `QlOs` is extended by several classes, but doesn't serves well as a base class: its implementation is very Intel-oriented, which is irrelevant to some other OS classes, and some of the OS "core" features are unnecessarily re-implemented by the extending classes. Consider extracting the Intel stuff out of the `QlOs` class, providing only generic implementation to OS derivatives - and on the other hand, minimize unnecessary implementation duplication across OS derivatives.

Another thing I realized when I worked on this class, is that some OS derivatives share the same `print_function` method, but use different / ambiguous type tags for the parameters. That may cause some of the parameters to be interpreted in an unexpected way (e.g. `BOOL` is 8-bits on some systems, but 32-bits on others; `VA_ARGS` may be implemented in different ways).

**Comment by xwings** [comment]
totally agree.

The story behind is: different people wrote the code at the same time. I guess you can see the coding style is different.

Refactoring is always on going and i guess we got long way to go.

Feel free to join in the fun :)

**Comment by xwings** [comment]
these code will be affecting ida pro, @kabeor  needs to check before we can merge it

**Comment by kabeor** [comment]
IDA Pro 7.5 test pass

**Comment by xwings** [comment]
Cool :)

**Comment by xwings** [comment]
I revert this merge. Looks like it kill sality test. let me try to bring sality back to the CI

**Comment by elicn** [comment]
Sality tries to access a function call parameter beyond the 12th.
Fixed by increasing supported number of arguments to 16 to make it happy.
Resubmitting the fixed version.

**Comment by xwings** [comment]
I am still having issue with others, sality too. I still cannot replicate in my box locally. let me check

**Comment by elicn** [comment]
Sality is totally broken.
I'll fix it too.

**Pull request merged**
