### PR TITLE
fix syscall open, openat open_flags_mapping

### PR DESCRIPTION
**Pull request by ucgJhe**
use the right function under debug mode, related to https://github.com/qilingframework/qiling/commit/156ccdeee4f95e933c955c08b7a605a430035278

### CODE REVIEW

**Comment by ucgJhe** [comment]
@xwings let me know if its broken , will check how i can help.

**Comment by xwings** [comment]
seems like fail at travis-ci, can you please run test/test-all.py to confirm

**Comment by xwings** [comment]
there you go, 

https://api.travis-ci.com/v3/job/296819829/log.txt

```
[+] load 0x555555564d80 - 0x555555565010
[+] mem_start: 0x0 mem_end: 0x12000
[+] interp is : ../examples/rootfs/arm64_linux/lib/ld-linux-aarch64.so.1
[+] interp_mem_size is : 0x2f000
[+] interp_base is : 0x7ffff7dd5000
[+] mmap_start is : 0x7ffff3dd6000
brk(0x0)
[+] brk return(0x555555566000)
uname(0x7fffffffe508) = 0
facccessat (18446744073709551516, 0x7ffff7def5a0, 0x0) = -1
[!] File Not Found or Skipped: /etc/ld.so.nohwcap
facccessat (18446744073709551516, 0x7ffff7dee660, 0x4) = -1
[!] File Not Found or Skipped: /etc/ld.so.preload
openat(-100, /etc/ld.so.cache, 0x80000, 0o0) = -1
[!] SYSCALL ERROR: ql_syscall_openat
[-] 'NoneType' object is not callable
[+] PC= 0x5b0
[+] 555555554000 - 555555566000      /home/travis/build/qilingframework/qiling/examples/rootfs/arm64_linux/bin/arm64_hello
[+] 7ffff7dd5000 - 7ffff7e04000      /lib/ld-linux-aarch64.so.1
Ebrk(0x0)
brk(0x483f70)
uname(0x7fffffffeba8) = 0
readlinkat(0xffffffffffffff9c, 0x4625a0, 0x7fffffffdca0, 0x1000) = -1
facccessat (18446744073709551516, 0x462180, 0x0) = -1
brk(0x4a4f70)
brk(0x4a5000)
fstat64(1, 0x7fffffffeba8) = 0
```

**Comment by ucgJhe** [comment]
it failed bcuz there is no open flags mapping for arm, arm64. ill add it later.

**Comment by ucgJhe** [comment]
close for now will reopen after its done

**Comment by xwings** [comment]
hi,

few comments,

1. arm_arm64_file_mapping, should it be arm only ?
2. arm_file mapping and arm64_file mapping this two function is the same, you can just do arm_file = arm64_file python take function as a var, u can just do this
3. between functions should have double line spacing.

thanks for the PR, looking forward !

**Comment by ucgJhe** [comment]
They(linux, arm, arm64) actually share one open flags constant at least for what we focused now, so I am keeping the arm_open_flags_mapping function.

**Comment by xwings** [comment]
Hi,

those unused code in test_elf.py please remove it. 
unless there is a reason to keep it, it so, please leave a comment there

**Comment by ucgJhe** [comment]
I was intend to add syscall testing for ARM in the first place, but got an issue for making arm executable binary.
will add comment for that.

**Comment by xwings** [comment]
Sure, add in the reasons why you need to comment out those sections.

**Comment by xwings** [comment]
Hi,

That's all for now. Thanks for the PR

**Pull request merged**
