### PR TITLE
Feature: add Qdb as built-in debugger for Qiling Framework

### PR DESCRIPTION
**Pull request by ucgJhe**
a gdb-like built-in debugger for Qiling Framework, support step-by-step execution so you can do manual check the runtime state of you target easily
its only MIPS supported for new, the rest were on the way.

### CODE REVIEW

**Comment by ucgJhe** [comment]
attach Qdb during the runtime
image

**Comment by aquynh** [comment]
What are differences between this and the current gdbserver?

**Comment by ucgJhe** [comment]
> What are differences between this and the current gdbserver?

no more tricky setup between server and client and less effort to make it work as a simple debugger, also somehow provide better UX than `output="debug"`

**Comment by aquynh** [comment]
Please have more details in README

**Comment by xwings** [comment]
Nice Job!

**Pull request merged**
