### PR TITLE
Fix directory traversal bug

### PR DESCRIPTION
**Pull request by nmantani**
I have added normalize() function to fix the directory traversal bug reported in #572.

### CODE REVIEW

**Comment by xwings** [comment]
Hi，

please update changelog too :)

thanks.

**Comment by wtdcode** [comment]
Thanks for the fix. Could you please add some relevant tests for your commits?

**Comment by nmantani** [comment]
I have found that I created my fix-directory-traversal branch from master not from dev branch.
Should I close this PR and open another PR with the branch re-created from dev branch?

**Comment by nmantani** [comment]
I am writing a test script for PathUtils functions and I found that current implementation of normalize() cannot handle Windows UNC paths correctly. I will fix it.

**Comment by wtdcode** [comment]
Yes, you should make your branch based on dev branch.

________________________________

**Comment by nmantani** [comment]
@wtdcode Thank you, I will make a branch based on dev branch and open another PR when I am ready.

**Comment by nmantani** [comment]
This pull request is superseded by #579  .

**Pull request closed without merging**
