### PR TITLE
Improved handling of export table for invalid export address and removed GandCrab workaround in GetProcAddress

### PR DESCRIPTION
**Pull request by clairelevin**
Binaries with an invalid export address table cause Qiling to crash when attempting to load exports. This fix ensures that pefile has loaded the export table before attempting to parse the exports.

Additionally, the hook for GetProcAddress contains a workaround for GandCrab that returns 0 when looking for RtlComputeCrc32. This causes other emulated binaries using the RtlComputeCrc32 API to fail, which makes me think this workaround was included unintentionally.

### Which kind of PR do you create?

- [X] This PR only contains minor fixes.
- [ ] This PR contains major feature update.
- [ ] This PR introduces a new function/api for Qiling Framework.

### Coding convention?

- [X] The new code conforms to Qiling Framework naming convention.
- [X] The imports are arranged properly.
- [X] Essential comments are added.
- [X] The reference of the new code is pointed out.

### Extra tests?

- [X] No extra tests are needed for this PR.
- [ ] I have added enough tests for this PR.
- [ ] Tests will be added after some discussion and review.

### Changelog?

- [X] This PR doesn't need to update Changelog.
- [ ] Changelog will be updated after some proper review.
- [ ] Changelog has been updated in my PR.

### Target branch?

- [X] The target branch is dev branch.

### One last thing

- [X] I have read the [contribution guide](https://docs.qiling.io/en/latest/contribution/)

-----

### CODE REVIEW

**Comment by elicn** [comment]
Doesn't the check on line 551 help avoid this situation?

**Comment by clairelevin** [comment]
The check on line 551 can fail if the export table exists, but is malformed. In that situation, the IMAGE_DIRECTORY_ENTRY_EXPORT attribute is present, but when pefile.full_load() is called, it can't parse the export table. Because of this, the DIRECTORY_ENTRY_EXPORT attribute never gets created, so Qiling crashes when it tries to access it.

**Comment by elicn** [comment]
OK, then better document that just above that line (something like: "address a corner case where ...."), because it might look redundant for someone who is not familiar with that exact corner case.

Also, please break the `if` statement so the `return` appears on a different line.

**Comment by clairelevin** [comment]
Ok, I've made the changes.

**Comment by xwings** [comment]
@elicn are you ok with the updates

**Review by elicn — APPROVED** [review]

**Review by kabeor — APPROVED** [review]

**Comment by kabeor** [comment]
Thanks, merged.

**Pull request merged**
