### PR TITLE
Bugfix: unaligned access in MIPS getdents64

### PR DESCRIPTION
**Pull request by tats-gd**
### Which kind of PR do you create?

- [X] This PR only contains minor fixes.
- [ ] This PR contains major feature update.
- [ ] This PR introduces a new function/api for Qiling Framework.

### Coding convention?

- [X] The new code conforms to Qiling Framework naming convention.
- [ ] The imports are arranged properly.
- [X] Essential comments are added.
- [ ] The reference of the new code is pointed out.

### Extra tests?

- [X] No extra tests are needed for this PR.
- [ ] I have added enough tests for this PR.
- [ ] Tests will be added after some discussion and review.

### Changelog?

- [X] This PR doesn't need to update Changelog.
- [ ] Changelog will be updated after some proper review.
- [ ] Changelog has been updated in my PR.

### Target branch?

- [ ] The target branch is dev branch.

### One last thing

- [X] I have read the [contribution guide](https://docs.qiling.io/en/latest/contribution/)

-----

### CODE REVIEW

**Comment by xwings** [comment]
Hi,

Welcome to Qiling Framework. 

Your PC need to to merge to dev and not master. thanks

**Comment by xwings** [comment]
Hi, 

The code seems to break the test. I need to revert it. Will you be able to make another PR ?

**Comment by tats-gd** [comment]
I have run the tests and they pass on my end, should I create a new PR?

**Comment by heck-gd** [comment]
@xwings Since no changes are required and this PR was not the cause of the breakage, you should be able to just cherry-pick commit 6bc1a3dbab2a019419cb3269b156d7ec1ec6b3cb onto the dev branch again rather than requesting a new PR.

**Comment by xwings** [comment]
Its better for a new PR and let it run thru the test. let the rest of the team comment it too

**Pull request merged**
