### PR TITLE
Improve the check for existance of address mapping

### PR DESCRIPTION
**Pull request by 0xPhoeniX**

### CODE REVIEW

**Comment by xwings** [comment]
is the another PR by you  too ?

**Comment by 0xPhoeniX** [comment]
No, it is not. Mine addresses the implementation of mmap/mmap2 syscall.
The other one an issues in elf loader.

**Comment by xwings** [comment]
my bad. so there are 3 mmap. mmap2 mmap and mmap old. i guess all of those also need the same check ?

**Comment by xwings** [comment]
and u r in the wrong base. i changed to dev. so, can u fix the conflict ?

**Comment by 0xPhoeniX** [comment]
Will do.

**Comment by 0xPhoeniX** [comment]
https://github.com/qilingframework/qiling/pull/324
Includes all the changes.

**Pull request closed without merging**
