### PR TITLE
Add windows 16bit compatibility file api

### PR DESCRIPTION
**Pull request by crass**
### Which kind of PR do you create?

- [ ] This PR only contains minor fixes.
- [ ] This PR contains major feature update.
- [x] This PR introduces a new function/api for Qiling Framework.

### Coding convention?

- [x] The new code conforms to Qiling Framework naming convention.
- [x] The imports are arranged properly.
- [x] Essential comments are added.
- [ ] The reference of the new code is pointed out. (**What does this mean?**)

### Extra tests?

- [x] No extra tests are needed for this PR. (**I don't believe there is testing of the winapi**)
- [ ] I have added enough tests for this PR.
- [ ] Tests will be added after some discussion and review.

### Changelog?

- [ ] This PR doesn't need to update Changelog.
- [ ] Changelog will be updated after some proper review.
- [x] Changelog has been updated in my PR. (**unsure if its necessary**)

### Target branch?

- [x] The target branch is dev branch.

### One last thing

- [x] I have read the [contribution guide](https://docs.qiling.io/en/latest/contribution/)

-----

This PR adds the [windows 16bit compatibility file api](https://docs.microsoft.com/en-us/windows/win32/api/winbase/)..

### CODE REVIEW

**Comment by xwings** [comment]
wow, this is amazing.

will take a serious look and will comment accordingly.

thanks!

**Comment by xwings** [comment]
First comment, 

will you be able to add a the following

1. binary
2. src
3. make a test case for it, it can be in test_pe.py

**Comment by crass** [comment]
> will you be able to add a the following
> 
>     1. binary

This binary is 38Mb. I could probably truncate it to ~5Mb and have it be usable. I would add it to the [rootfs repo](https://github.com/qilingframework/rootfs)?

>     2. src

Is this the source of the binary mentioned in 1? If so, I do not have the source. I also don't know the terms of redistribution, if that matters.

>     3. make a test case for it, it can be in test_pe.py

Adding a test case looks doable. Assuming nothing above is a deal breaker.

**Comment by xwings** [comment]
You are right. I am not sure are those dlls are ok to expose. but we still need a method to test

**Comment by crass** [comment]
I'm not a windows dev, nor have a windows dev environment setup. So creating such a binary, while not super hard to write a C file for, would be a pain for me to turn into an executable.

**Comment by xwings** [comment]
yup. i will note this in issue #333

**Pull request merged**
