### PR TITLE
Updates to posix/syscall/unistd.py and os/utils.py 

### PR DESCRIPTION
**Pull request by kxynos**

### CODE REVIEW

**Comment by xwings** [comment]
Hi,

I suggest you can merge read and write string in to one function and move to os/memory.py

so it will be ql.mem.string()

ql.mem.string(address) means read
ql.mem.string(address, value) means write

**Comment by xwings** [comment]
Let me know once you update the code !

**Comment by kxynos** [comment]
Code is ready. Do you want me to replace old ql_read_string too ?

**Comment by xwings** [comment]
what i am trying to say it. merge  your ql_writing_string into qiling/os/memory.py and make it 

ql.mem.string(address) means read
ql.mem.string(address, value) means write

**Comment by xwings** [comment]
i made changes to qiling/os/memory.py and u just need to integrate your code

**Comment by kxynos** [comment]
I am testing the code I wrote for qiling/os/memory.py and will upload it soon.

**Pull request closed without merging**
