### PR TITLE
add pstate in arm64

### PR DESCRIPTION
**Pull request by richor1042**
### Which kind of PR do you create?

- [x] This PR only contains minor fixes.
- [ ] This PR contains major feature update.
- [ ] This PR introduces a new function/api for Qiling Framework.

### Coding convention?

- [ ] The new code conforms to Qiling Framework naming convention.
- [ ] The imports are arranged properly.
- [ ] Essential comments are added.
- [ ] The reference of the new code is pointed out.

### Extra tests?

- [ ] No extra tests are needed for this PR.
- [x] I have added enough tests for this PR.
- [ ] Tests will be added after some discussion and review.

### Changelog?

- [ ] This PR doesn't need to update Changelog.
- [ ] Changelog will be updated after some proper review.
- [ ] Changelog has been updated in my PR.

### Target branch?

- [ ] The target branch is dev branch.

### One last thing

- [x] I have read the [contribution guide](https://docs.qiling.io/en/latest/contribution/)

-----

### CODE REVIEW

**Review by elicn — APPROVED** [review]

**Review by wtdcode — APPROVED** [review]

**Comment by kabeor** [comment]
Hi, plz rebase to dev branch.

**Comment by xwings** [comment]
@richor1042 i rebased there there is a conlict
will you be able to fix it.

**Comment by elicn** [comment]
@xwings you rebased on `master` rather than `dev`.
Can you revert this..?

**Comment by xwings** [comment]
@elicn no more code ? there are zero file changes

**Comment by elicn** [comment]
Not really, the issue was an inconsistent indentation, and I fixed it. Only whitespaces..

**Pull request closed without merging**
