### PR TITLE
tried to reformat codebase to be pep8 compliant

### PR DESCRIPTION
**Pull request by echel0nn**
### Which kind of PR do you create?

- [ ] This PR only contains minor fixes.
- [ ] This PR contains major feature update.
- [ ] This PR introduces a new function/api for Qiling Framework.

### Coding convention?

- [ ] The new code conforms to Qiling Framework naming convention.
- [ ] The imports are arranged properly.
- [ ] Essential comments are added.
- [ ] The reference of the new code is pointed out.

### Extra tests?

- [x] No extra tests are needed for this PR.
- [ ] I have added enough tests for this PR.
- [ ] Tests will be added after some discussion and review.

### Changelog?

- [ ] This PR doesn't need to update Changelog.
- [ ] Changelog will be updated after some proper review.
- [ ] Changelog has been updated in my PR.

### Target branch?

- [x] The target branch is dev branch.

### One last thing

- [x] I have read the [contribution guide](https://docs.qiling.io/en/latest/contribution/)

-----

the reformatted things are generally;
maximum line length:80
the comments are starting with the same alignment
removing trailing whitespaces
def and classes have exactly two newlines before it is defined
comments are starting with exactly one space
reformatted the alighment of lists and dicts's values
reformatted value{whitespace_here}: to value:{whitespace_here}
placed whitespace before and after operators
one-liner imports (where maximum line len>80) are seperated to multi-lines
hex number's characters are uppercase
changed ObjectName(): to ObjectName: (ex: class QlDebugger(): -> class Debugger:
single quote to double quotes
removed multiple whitespaces around an operator 
putting multi whitespaces is logical, it is more aligned imo. but pep8 doesn't like that multi whitespaces.
Did reformat with mostly `black` python library using the `-l 80` parameter.

### CODE REVIEW

**Comment by elicn** [comment]
IMOH this massive reformatting is going to do more harm than good.
I agree that coding conventions should be consistent across the codebase, but keep in mind that it includes emulation code for several OS. Each OS emulation code tries to follow that OS coding style, which may not be pep8 compliant (for example, datatypes in Windows are usually uppercase and method names in UEFI are CamelCase).

Some pep8 rules do not make sense in 2021 (are you still using an 80-chars wide terminal..?) and should not be applied.
I suggest to cherrypick the changes we want to apply to have as consistent codebase as possible, but pick the rules that make sense for this particular project.

**Comment by xwings** [comment]
I agree with the "80-chars wide terminal" is way too old school. I will not code without a 4k screen :)

**Comment by echel0nn** [comment]
I am agreeing with you guys, this PR is nothing but a try to open the discussion. because it looks like everyone is doing their best way or doing nothing about it. this confused me a lot when I did my first pull request.

**Comment by echel0nn** [comment]
So we talked with @xwings, i will try to reformat general things and will split changes into pieces so that the review will be easier. I am closing this PR

**Comment by elicn** [comment]
Thanks for bringing this up. I truly think consistent coding conventions are important for maintainable and welcoming code base.
I also think this is a good opportunity to establish a set of coding standard that would fit this project and that every new PR would be required to meet it.

**Pull request closed without merging**
