### PR TITLE
Add interactive pipe to simulate pwntools `interactive` function

### PR DESCRIPTION
**Pull request by anotherdish**
This pipe is intended to simulate the pwntools feature of being able to go into `interactive` mode, where users are able to interact with stdin of the process. 

### Which kind of PR do you create?

- [x] This PR introduces a new function/api for Qiling Framework.

### Coding convention?

- [x] The new code conforms to Qiling Framework naming convention.
- [x] The imports are arranged properly.
- [x] Essential comments are added.
- [x] The reference of the new code is pointed out.

### Extra tests?

- [x] No extra tests are needed for this PR.

(its hard to test the `input` call needed to test this properly, but if we need tests for it I can make something up)

### Changelog?

- [x] This PR doesn't need to update Changelog.

### Target branch?

- [x] The target branch is dev branch.

### One last thing

- [x] I have read the [contribution guide](https://docs.qiling.io/en/latest/contribution/)

-----

### CODE REVIEW

**Comment by chinggg** [comment]
Concept ACK.
Thanks for contributing! Can you add some examples to show how users can use the `interactive` mode?

**Comment by anotherdish** [comment]
sure thing. do you mind if i do the example in the qiling documentation repo? i wanted to do a unit test for this, but i didn’t figure out a good way to leave the code unchanged and still handle the `input` call

**Comment by anotherdish** [comment]
hey i added some [documentation](https://github.com/qilingframework/rtfd.io/pull/50) in the docs, let me know if that looks good or if you want something more

**Comment by chinggg** [comment]
LGTM. I just played your example and it seems to work well. I am not sure whether the `interactive` mode works for non-trival programs. @elicn What are your opinion?

**Comment by anotherdish** [comment]
ya this probably wont be super useful for many real world applications, but for little things like CTFs this kind of feature is a nice to have

**Comment by elicn** [comment]
The default `stdin` behavior is waiting for a user to type in their input.. I don't understand what is the added value here.
Can you give a concrete example in which the default behavior wouldn't work and this ont would be useful?

**Review by elicn — APPROVED** [review]

**Comment by xwings** [comment]
thanks for the PR.

**Review by xwings — APPROVED** [review]

**Pull request merged**
