### PR TITLE
Fix project metadata and Docker builds

### PR DESCRIPTION
**Pull request by mochaaP**
### Which kind of PR do you create?

- [x] This PR only contains minor fixes.
- [ ] This PR contains major feature updates.
- [ ] This PR introduces a new function/API for Qiling Framework.

### Coding convention?

- [ ] The new code conforms to Qiling Framework naming convention.
- [ ] The imports are arranged properly.
- [x] Essential comments are added.
- [ ] The reference of the new code is pointed out.

### Extra tests?

- [x] No extra tests are needed for this PR.
- [ ] I have added enough tests for this PR.
- [ ] Tests will be added after some discussion and review.

### Changelog?

- [x] This PR doesn't need to update Changelog.
- [ ] Changelog will be updated after some proper review.
- [ ] Changelog has been updated in my PR.

### Target branch?

- [x] The target branch is dev branch.

### One last thing

- [x] I have read the [contribution guide](https://docs.qiling.io/en/latest/contribution/)

-----

### CODE REVIEW

**Review by elicn — COMMENTED** [review]
Why removing the `if __name__ == '__main__'` statements?
It is not a Python 2 compliance; see Python 3 documentation [here](https://docs.python.org/3.11/library/__main__.html#idiomatic-usage)

**Comment by mochaaP** [comment]
It's not removed, it's wrapped into a `run` function so we can use it in the script entrypoint later.

**Comment by elicn** [comment]
Oh, I see.. I must have missed that.

**Comment by elicn** [comment]
@mochaaP, what's with that `.gitignore`? It is full of redundant auto-generated stuff. Can you reduce it to the absolute necessary?

**Comment by mochaaP** [comment]
I don't think that's a particularly big issue?

**Comment by mochaaP** [comment]
The gitignore is just <https://github.com/github/gitignore/blob/main/Python.gitignore> with a few extra additions (poetry local config, ruff cache and pyright config).

**Comment by mochaaP** [comment]
Hope this could get merged soon, currently waiting for this so we don't have to maintain a separate build step ourselves :)

**Comment by elicn** [comment]
We strive to keep the code clean as much as possible.
Please remove all redundant auto-generated additions.

**Comment by mochaaP** [comment]
Reduced to minimum while keeping the required for Poetry.

**Review by xwings — APPROVED** [review]

**Comment by mochaaP** [comment]
waiting for @elicn 👋

**Review by wtdcode — APPROVED** [review]

**Comment by mochaaP** [comment]
@xwings Ready for merge :)

**Review by elicn — APPROVED** [review]
`.gitignore` is still full of auto-generated stuff, but whatever.

**Comment by mochaaP** [comment]
Rebase & more cleanups.

**Pull request merged**
