### PR TITLE
add support for mips32_lkm

### PR DESCRIPTION
**Pull request by cq674350529**
The main changes are as following:
1. add support for mips32_lkm;
2. fix lkm mapping.

Currently, when loading the lkm, it simply maps the elfdata into memory. However, some sections such as `.bss` don't exist in the original lkm. Due to lack of the `.bss` section in memory, error will occur when encoutering instructions containing `.bss` data references.
https://github.com/qilingframework/qiling/blob/d59436e673a0f7feaf3865cf0fb9245d4ec0d3a5/qiling/loader/elf.py#L596-L603

Since there are no program headers in lkm, so just map the necessary sections by parsing the lkm.

PS: It may not be prefect, but indeed work in some cases, at least for me.

### CODE REVIEW

**Comment by xwings** [comment]
Please update change log too :)

**Comment by xwings** [comment]
Like x86 32bit, we might need a test file too ? 

a simple one will work. this is to prevent we screw up the code in the future

**Comment by cq674350529** [comment]
Ok, I'll have a try. Currently, the mips lkm binary I test against is for private use and not convenient to share.

**Comment by xwings** [comment]
cool, thanks!

a helloworld or something will be really good.

**Comment by xwings** [comment]
also,

just dropped u an email on your  @163 addy.

**Comment by cq674350529** [comment]
Another change: filter out unnecessary sections when doing relocations.

If a lkm is compiled with debug info, then there are some sections related to `debug info`. For sections such as `.rel.debug_info` and `.rel.debug_arange`, relocation will be done against these sections in current implementation. However, since these sections won't be loaded into memory either, error will occur when doing relocations.

I resort to some open projects such as `angr`, and the filter logic is learnt from their work.

```
Section Headers:
  [Nr] Name              Type            Addr     Off    Size   ES Flg Lk Inf Al
  [ 0]                   NULL            00000000 000000 000000 00      0   0  0
  [ 1] .note.gnu.build-i NOTE            00000000 000034 000024 00   A  0   0  4
  [ 2] .text             PROGBITS        00000000 000060 000000 00  AX  0   0 16
  [ 3] .init.text        PROGBITS        00000000 000060 00002c 00  AX  0   0  4
  [ 4] .rel.init.text    REL             00000000 016f00 000020 08   I 33   3  4
  [ 5] .exit.text        PROGBITS        00000000 00008c 000014 00  AX  0   0  4
  [ 6] .rel.exit.text    REL             00000000 016f20 000020 08   I 33   5  4
  [ 7] .reginfo          MIPS_REGINFO    00000000 0000a0 000018 18   A  0   0  4
  [ 8] .MIPS.abiflags    MIPS_ABIFLAGS   00000000 0000b8 000018 18   A  0   0  8
  [ 9] .rodata.str1.4    PROGBITS        00000000 0000d0 000030 01 AMS  0   0  4
  [10] .modinfo          PROGBITS        00000000 000100 000050 00   A  0   0  4
  [11] __versions        PROGBITS        00000000 000150 000080 00   A  0   0  4
  [12] .data             PROGBITS        00000000 0001d0 000000 00  WA  0   0 16
  [13] .gnu.linkonce.thi PROGBITS        00000000 000200 000200 00  WA  0   0 64
  [14] .rel.gnu.linkonce REL             00000000 016f40 000010 08   I 33  13  4
  [15] .bss              NOBITS          00000000 000400 000000 00  WA  0   0 16
  [16] .pdr              PROGBITS        00000000 000400 000040 00      0   0  4
  [17] .rel.pdr          REL             00000000 016f50 000010 08   I 33  16  4
  [18] .mdebug.abi32     PROGBITS        00000000 000440 000000 00      0   0  1
  [19] .comment          PROGBITS        00000000 000440 00005c 01  MS  0   0  1
  [20] .gnu.attributes   GNU_ATTRIBUTES  00000000 00049c 000010 00      0   0  1
  [21] .debug_info       MIPS_DWARF      00000000 0004ac 00d2ee 00      0   0  1
  [22] .rel.debug_info   REL             00000000 016f60 006190 08   I 33  21  4
  [23] .debug_abbrev     MIPS_DWARF      00000000 00d79a 0005a4 00      0   0  1
  [24] .debug_aranges    MIPS_DWARF      00000000 00dd3e 000040 00      0   0  1
  [25] .rel.debug_arange REL             00000000 01d0f0 000020 08   I 33  24  4
  [26] .debug_ranges     MIPS_DWARF      00000000 00dd7e 000018 00      0   0  1
  [27] .rel.debug_ranges REL             00000000 01d110 000020 08   I 33  26  4
  [28] .debug_line       MIPS_DWARF      00000000 00dd96 000bb3 00      0   0  1
  [29] .rel.debug_line   REL             00000000 01d130 000010 08   I 33  28  4
  [30] .debug_str        MIPS_DWARF      00000000 00e949 008242 01  MS  0   0  1
  [31] .debug_frame      MIPS_DWARF      00000000 016b8c 00003c 00      0   0  4
  [32] .rel.debug_frame  REL             00000000 01d140 000020 08   I 33  31  4
  [33] .symtab           SYMTAB          00000000 016bc8 000250 10     34  33  4
  [34] .strtab           STRTAB          00000000 016e18 0000e8 00      0   0  
```

**Comment by xwings** [comment]
cool, let me take a look
can u also add a test for x86 32bit ? helloworld will do. i do remember we dont have such test.

**Comment by cq674350529** [comment]
There exists a test for x86 32bit lkm already. However it runs in `disasm` mode.

https://github.com/qilingframework/qiling/blob/8eaa22d2eb6849be76dc9a95ce24659da887258b/tests/test_elf.py#L1167-L1185

**Comment by xwings** [comment]
i will retest this PR once we move in the new refactor.

you might need to do some update.

**Comment by xwings** [comment]
There is a conflict after the refactor.  would you be able to update it ? thanks

**Comment by xwings** [comment]
thanks !

**Pull request merged**
