### PR TITLE
update doc,docker,travis,dll script

### PR DESCRIPTION
**Pull request by chfl4gs**
- Enabled docker build on Travis-CI
- Updated documentation: added pyenv by 0ssigeno
- Dockerfile reverted for complete docker image building
- Updated credit.txt following naming convention
- Updated dllcollector script for new dlls.
- Clean-up on README.md

### CODE REVIEW

**Comment by 0ssigeno** [comment]
Please correct me if I'm wrong, I'm no way an expert in docker.
I undestand why you want to do a git clone, but I thought that docker container could be used to have a stable environment for development.
Everytime something change on the qiling repo, the container must be rebuild, but with a copy from the local repo, that a user must have cloned, this problem doesn't appear.

**Comment by xwings** [comment]
Hi,

The docker file must designed for new users. The image itself dosent have the cloned code. I guess that is why we need it.

**Comment by xwings** [comment]
I will merge it. @0ssigeno comments always welcome in issue and gitter :)

**Comment by chfl4gs** [comment]
This is correct way to use docker. If you have updates, you need to rebuild docker images and deploy to your container. The idea is to containerized application for rapid deployment i.e. for person who would want to use without modification. For you usage, I'd suggest bind mount of source code where you can constantly update without rebuilding docker image. You can find more information on docker concept at https://docs.docker.com/engine/docker-overview/

**Comment by 0ssigeno** [comment]
@chfl4gs thank you for your explanation, I didn't know it was the best practice with Docekr!

**Comment by chfl4gs** [comment]
@0ssigeno no worries, mate! Thanks for contributing to the project. For your usage, you could run something like this. Bind mount your current dev Qiling Framework directory and run installation for your container.

```
docker build -t qiling:1.0 .
docker run -dt --name qiling -v $PWD/qiling:/qiling qiling:1.0
docker exec qiling bash -c "python3 setup.py install"
```

**Pull request merged**
