### PR TITLE
Fix use pread/pwrite when unavailable

### PR DESCRIPTION
**Pull request by tututu-patch**
### Which kind of PR do you create?

- [√ ] This PR only contains minor fixes.
- [ ] This PR contains major feature update.
- [ ] This PR introduces a new function/api for Qiling Framework.

### Coding convention?

- [ ] The new code conforms to Qiling Framework naming convention.
- [ ] The imports are arranged properly.
- [ ] Essential comments are added.
- [ ] The reference of the new code is pointed out.

### Extra tests?

- [ ] No extra tests are needed for this PR.
- [ ] I have added enough tests for this PR.
- [ ] Tests will be added after some discussion and review.

### Changelog?

- [ ] This PR doesn't need to update Changelog.
- [ ] Changelog will be updated after some proper review.
- [ ] Changelog has been updated in my PR.

### Target branch?

- [ ] The target branch is dev branch.
- [√ ] master branch

### One last thing

- [ ] I have read the [contribution guide](https://docs.qiling.io/en/latest/contribution/)

-----

### CODE REVIEW

**Comment by wtdcode** [comment]
Hi, why do you need this patch?

**Comment by tututu-patch** [comment]
Some Python OS modules do not have the pread attribute. Then he will report an error.

**Comment by wtdcode** [comment]
> Some Python OS modules do not have the pread attribute. Then he will report an error.

Could you provide a sample source or test binary? btw, you are failing CI.

**Comment by tututu-patch** [comment]
My English is not good. Can I add your wechat?

**Comment by wtdcode** [comment]
> My English is not good. Can I add your wechat?

You may reach me via pwnedmio.

**Comment by xwings** [comment]
> My English is not good. Can I add your wechat?

the CI test failed :)

**Comment by tututu-patch** [comment]
> 

Yes, I have communicated with @wtdCode that other systems will fail if I change them this way.

**Comment by xwings** [comment]
Close for now

**Pull request closed without merging**
