### PR TITLE
Add support for MAP_FIXED + mmap system call refactoring

### PR DESCRIPTION
**Pull request by 0xPhoeniX**
### Which kind of PR do you create?

- [x] This PR only contains minor fixes.
- [ ] This PR contains major feature update.
- [ ] This PR introduces a new function/api for Qiling Framework.

### Coding convention?

- [x] The new code conforms to Qiling Framework naming convention.
- [ ] The imports are arranged properly.
- [ ] Essential comments are added.
- [ ] The reference of the new code is pointed out.

### Extra tests?

- [x] No extra tests are needed for this PR.
- [ ] I have added enough tests for this PR.
- [ ] Tests will be added after some discussion and review.

### Changelog?

- [ ] This PR doesn't need to update Changelog.
- [x] Changelog will be updated after some proper review.
- [ ] Changelog has been updated in my PR.

### Target branch?

- [x] The target branch is dev branch.

### One last thing

- [x] I have read the [contribution guide](https://docs.qiling.io/en/latest/contribution/)

-----

### CODE REVIEW

**Comment by bet4it** [comment]
You should remove trailing whitespace

**Comment by 0xPhoeniX** [comment]
@bet4it should be fixed now.

**Comment by wtdcode** [comment]
Thanks for your PR.

One question: Why would you like to refactor the mmap syscall?

**Comment by 0xPhoeniX** [comment]
@wtdcode because when I fixed the bug in one system call, I needed to write the same code twice in other mmap version.
It looks to me that having the same code in one function will make it

- much less effort to maintain code
- prevent bugs
- reduce code duplication (the very first thing that I was  taught during sw engineering courses)

Do you have other thoughts ?

**Comment by xwings** [comment]
Cool,

i think we got similar call for macos. Can we merge it in to 1 ?

**Comment by 0xPhoeniX** [comment]
@xwings - is this the right place for mmap implementation -> https://github.com/qilingframework/qiling/blob/master/qiling/os/macos/syscall.py ?

As you know qiling arch better, any suggestions where to move the common implementation of `mmap` to use it across platforms ?

**Comment by bet4it** [comment]
You may refer to this commit: ac73e1eb61b40d3b56283b9bf68e77e6429b9267

**Comment by 0xPhoeniX** [comment]
> Cool,
> 
> i think we got similar call for macos. Can we merge it in to 1 ?

Done.

**Comment by 0xPhoeniX** [comment]
@xwings Hey, can you please fix CI/CD pipeline to point to the right file : https://github.com/qilingframework/rootfs/raw/master/x8664_macos/System/Library/Kernels/kernel.development ?

That should fix the test.

**Comment by wtdcode** [comment]
> @xwings Hey, can you please fix CI/CD pipeline to point to the right file : https://github.com/qilingframework/rootfs/raw/master/x8664_macos/System/Library/Kernels/kernel.development ?
> 
> That should fix the test.

That line is commented already. You could merge the latest dev branch to yours and the CI shall pass.

**Comment by 0xPhoeniX** [comment]
@xwings
```
open(/private/var/db/dyld/dyld_shared_cache_x86_64, O_RDONLY, 0o0) = -2
[+] QlThread None	File Not Found /Users/distiller/project/tests/../examples/rootfs/x8664_macos/private/var/db/dyld/dyld_shared_cache_x86_64
[+] QlThread None	open() = -0x2 (ENOENT)
```
Most probably fails the test. When I was testing locally with dyld (> 1Gb) present, the test succeeded.

**Comment by xwings** [comment]
Hi,

Just remove the code if not needed. Then I will merge it.

Thanks!

**Comment by 0xPhoeniX** [comment]
@xwings  - what code?

**Comment by xwings** [comment]
there are some unused code which is being comment out ?

**Comment by 0xPhoeniX** [comment]
@xwings  - done. 

Do note: I suggest to to leave the comment for mmap2 syscall so that others will be aware how the mmap2 for mac is implemented in qiling

**Comment by xwings** [comment]
Actually, if the syscall is not using in macos. we should just remove it as well. 

the reason why there is a macos os mmap is due to the incompatibility and quick fix. 

since we got it all working now. we should just remove it.

**Comment by 0xPhoeniX** [comment]
@xwings  should be all fixed now.

**Comment by xwings** [comment]
Cool, thanks

**Pull request merged**
