### PR TITLE
Fix memory search to handle range overlaps correctly

### PR DESCRIPTION
**Pull request by andrwnoskov**
Fix issue #904 
### Which kind of PR do you create?

- [x] This PR only contains minor fixes.
- [ ] This PR contains major feature update.
- [ ] This PR introduces a new function/api for Qiling Framework.

### Coding convention?

- [x] The new code conforms to Qiling Framework naming convention.
- [x] The imports are arranged properly.
- [x] Essential comments are added.
- [ ] The reference of the new code is pointed out.

### Extra tests?

- [ ] No extra tests are needed for this PR.
- [x] I have added enough tests for this PR.
- [ ] Tests will be added after some discussion and review.

### Changelog?

- [ ] This PR doesn't need to update Changelog.
- [x] Changelog will be updated after some proper review.
- [ ] Changelog has been updated in my PR.

### Target branch?

- [x] The target branch is dev branch.

### One last thing

- [x] I have read the [contribution guide](https://docs.qiling.io/en/latest/contribution/)

-----

### CODE REVIEW

**Comment by andrwnoskov** [comment]
Please note, the initial code was
```(begin <= lbound < end) or (begin < ubound <= end)```, which probably had to be
```(lbound <= begin < ubound) or (lbound < end <= ubound)```, but meant `(lbound <= begin < ubound) or (lbound < end < ubound)`

Isn't it?

**Comment by andrwnoskov** [comment]
Current code treats ranges as `[a, b]`, which means if we have intersection on the ends, there will be an overlap.
For example: `[1, 5] and [5, 8] - overlap`

Is that correct? Or it should be `[1, 5) and [5, 8] - no overlap`

**Comment by xwings** [comment]
Thanks and super thanks! few suggestion
1. update change log, this is a important fix
2. add in a test in test_elf.py. make sure no one mess with this next time.

**Comment by elicn** [comment]
There is no problem of overlap really.. the range is used to calculate base + size, so effectively there is no overlap.
Taking you example, where there are two ranges `[1, 5]` and `[5, 8]`: the first range will be taken as `base = 1` and `size = 5 - 1`, so no overlap here.

**Comment by xwings** [comment]
Not too sure this got any issue with PE loader. Need to investigate abit more.

**Comment by xwings** [comment]
okay, issue was the pefile module. i downgraded to  one older version.

**Pull request closed without merging**
