### PR TITLE
add syscall getdents for both linux x86 and x86_64

### PR DESCRIPTION
**Pull request by ucgJhe**
implement syscall getdents for #165 , but command "ls" still not working its more than just a simple syscall.

### CODE REVIEW

**Comment by xwings** [comment]
NIce,

Can you add this to other arch as well ?

also. If we have these syscall in posix/syscall.py can we add it in into x8664 ?

```
[!] 0x7ffff488beb3: syscall number = 0xda(218) not implement
[!] 0x7ffff488bf15: syscall number = 0x111(273) not implement
[!] 0x7ffff488bff1: syscall number = 0xe(14) not implement
[!] 0x7ffff4134f9e: syscall number = 0x12e(302) not implement
[!] 0x7ffff412e975: syscall number = 0x89(137) not implement
[!] 0x7ffff412e975: syscall number = 0x89(137) not implement
```

if we dont have it, that is fine.

**Comment by xwings** [comment]
Can you try to run /bin/ls again ? Seems like having issue now

**Comment by ucgJhe** [comment]
after disabled syscall sigprocmask its working again

**Comment by ucgJhe** [comment]
turns out its a typo issue , should be good now

**Comment by xwings** [comment]
Nice work! Thanks !

**Pull request merged**
