### PR TITLE
Implement futex bitset && Check library initialization

### PR DESCRIPTION
**Pull request by JackGrence**
- Implement FUTEX_WAIT_BITSET and FUTEX_WAKE_BITSET flag of futex syscall.
- Check library init successfully or not.
    - futex syscall still has some features not implemented. It will `ql.emu_stop()` at [here](https://github.com/JackGrence/qiling/blob/futex_bitset/qiling/os/posix/syscall/futex.py#L69). If a library's `.init()` (like libpthread) use the unimplemented feature, emulator will stop in `.init()` function and start from elf's entry point. Will cause some unexpected status.

### CODE REVIEW

**Comment by xwings** [comment]
Hi,

can you also please upgrade changelog with this "Implement futex bitset && Check library initialization" ?

**Comment by xwings** [comment]
sorry,

its "Linux: Implement futex bitset && Check library initialization"

**Comment by JackGrence** [comment]
Sure!

**Comment by xwings** [comment]
Thanks!

**Pull request merged**
