### PR TITLE
add syscall truncate, ftruncate

### PR DESCRIPTION
**Pull request by ucgJhe**
as title.

### CODE REVIEW

**Comment by xwings** [comment]
Hi,

Thanks and thanks again

I do not think we we have any binary making this syscall. 
Do you have any sample binary that you can upload to rootfs/xxx/ accordingly ?

If possible update tests/test_elf.py ?w

**Comment by xwings** [comment]
Does this syscall match to any arch ?

**Comment by ucgJhe** [comment]
I ran into this , bcuz i try to run some mipsr32el firmware with qiling . I don't have any single binary example for specific syscall. if you need it i would try to make some binaries and add it to tests.

**Comment by xwings** [comment]
Two Questions,

1. If possible, having a binary to test will be really great.
2. Just wondering how "far" we can run the firmware. Good ? Bad? or Shit!

**Comment by ucgJhe** [comment]
> Two Questions,
> 
> 1. If possible, having a binary to test will be really great.
> 2. Just wondering how "far" we can run the firmware. Good ? Bad? or Shit!

1. One binary for one syscall is good ? or several relatives syscall into one binary (ex. unlink , truncate ...) is better ?
2. There are still some barriers like
 - syscall: clone, poll ...
 - sometimes firmware service needs other dependency service at runtime etc.

**Comment by xwings** [comment]
One binary will do.

You can always make wrapper to make it looks like system services or fake nvram.

**Comment by ucgJhe** [comment]
Just add a test for truncate and ftruncate, and use ql_read_string to fix #53 instead of custom mem_read

**Comment by xwings** [comment]
mips32el_syscall can rename to mips32el_syscall_truncate maybe ? 
feel free to upload src code to rootfs/src 

what is in text.txt ? we remove if we dont need it.

**Comment by ucgJhe** [comment]
> mips32el_syscall can rename to mips32el_syscall_truncate maybe ?
> feel free to upload src code to rootfs/src
> 
> what is in text.txt ? we remove if we dont need it.

1. I thought use one binary to test all sysycall ? if we don't then I will rename the binary
2. test.txt is a workaround for #58 will remove it after its fixed

**Comment by xwings** [comment]
maybe posix_trancate_series.bin or something. syscall is too wide

**Comment by xwings** [comment]
there is a bug in llseek and we updated it.
there is a conflct. can you update it

**Comment by ucgJhe** [comment]
accept the patch and will make another test for that

**Comment by xwings** [comment]
mips32el_syscall.c  maybe can rename into posix_syscall.c ?
will you be able to to make more easier so we can add more syscall for testing next time?

so next time we will not have too many test.c all will be in posix_syscall.c ?

test.txt maybe can rename to test_syscall.txt ?

**Comment by ucgJhe** [comment]
> mips32el_syscall.c maybe can rename into posix_syscall.c ?
> will you be able to to make more easier so we can add more syscall for testing next time?
> 
> so next time we will not have too many test.c all will be in posix_syscall.c ?
> 
> test.txt maybe can rename to test_syscall.txt ?

yeah , that's what i talking about one syscall for one binary or what so ever.
so gather all syscall into one binary for testing, right ?

I will just delete and create all necessary testing files in test_elf.py

**Comment by xwings** [comment]
current test can leave it there. 

if you able to make more syscall for the posix_syscall.c it will be really prefect.

We had almost 100 syscall right now. not easy to finish all. you can pick and choose !

**Comment by ucgJhe** [comment]
1. fix #58 first, no need for test.txt at all
2. rename mips32el_syscall to mips32el_posix_syscall
3. will use same posix_sycall.c in the future but complied to different arch for testing

@xwings did I get it right ?

**Comment by ucgJhe** [comment]
maybe failed cuz improper logic in posix/util.py:40-41
I don't have any OSX device to do more test , just wait for someone to solve it

**Comment by xwings** [comment]
看来有点误会 我解释一下哈

你的测试.c 可以改名字成为 posix_sycall.c  然后里面可以慢慢加入更多的syscall 你可以修改一下posix_sycall.c 成为一个简单的格式方便以后大家便测试新syscall  也就是说 以后有新syscall 直接在你的posix_sycall.c加入一段然后编译 更新就可以了  

不一定是mipsel 在交叉编译posix_sycall.c 的时候可以选定要的框架 生产就可以  在Makefile 里边生成就可以了

**Comment by ucgJhe** [comment]
> 看来有点误会 我解释一下哈
> 
> 你的测试.c 可以改名字成为 posix_sycall.c 然后里面可以慢慢加入更多的syscall 你可以修改一下posix_sycall.c 成为一个简单的格式方便以后大家便测试新syscall 也就是说 以后有新syscall 直接在你的posix_sycall.c加入一段然后编译 更新就可以了
> 
> 不一定是mipsel 在交叉编译posix_sycall.c 的时候可以选定要的框架 生产就可以 在Makefile 里边生成就可以了

1. 目前推上去的東西大概符合，除了 posix_syscall.c 格式以外
2. 會推上 mipsel_posix_syscall 的原因是為了 tests/test_elf.py 可以運作

其他理解有錯誤嗎?

**Comment by xwings** [comment]
对的 

帮个忙整理一下posix_syscall.c 就ok了

谢谢！

**Comment by ucgJhe** [comment]
除了用 comment 隔開每個 syscall 以外，我想不到其他更好的方式，有什麼建議嗎?

**Comment by xwings** [comment]
现在macos不会卡了  你测试看看 

posix_syscall.c 的问题 等 @chenhuitao 来解答

**Comment by chenhuitao** [comment]
我的建议是写一个static函数来处理调用对应syscall的上下文，main中再调用这样的函数就可以了，这样应该更优雅也更独立一些。
还有就是请在对应的测试调用中，需要对返回值（预期值加入判断），加入一些输出信息，至少包含当前的syscall名称和返回值。
@ucgJhe 您觉得如何？

**Comment by xwings** [comment]
@chenhuitao 建议你修改 那个C测试代码

**Comment by ucgJhe** [comment]
> 我的建议是写一个static函数来处理调用对应syscall的上下文，main中再调用这样的函数就可以了，这样应该更优雅也更独立一些。
> 还有就是请在对应的测试调用中，需要对返回值（预期值加入判断），加入一些输出信息，至少包含当前的syscall名称和返回值。
> @ucgJhe 您觉得如何？

這是一個好主意，但我在想某些操作會互相依賴，例如 truncate 必須要先有 open 等

是否還有需要個別測試 open 抑或是每個 function 各自獨立，不管其他 function 是否已經使用過這些 syscall 了

**Comment by chenhuitao** [comment]
一个函数可以测试多个syscall。关联的一系列操作不管其他的函数是否实现，独立在自己的函数内进行调用和判断。常见的open等函数可能会重复测试很多次，这个代价我觉得可以接受，并且不同上下文中的open也可以独立测试到。

**Comment by ucgJhe** [comment]
```c
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>

#define TEST_FILENAME "test_syscall.txt"

typedef void (*funcptr)();

static int syscall_open() {

    FILE *pFile;

    pFile = fopen(TEST_FILENAME, "a+");

    fclose(pFile);

    return 0;
}

static int syscall_truncate() {

    FILE *pFile;

    char buffer[] = "Hello testing";

    pFile = fopen(TEST_FILENAME, "w+");

    if (pFile == NULL) return 1;

    fwrite(buffer, 1, sizeof(buffer), pFile);

    fclose(pFile);

    return truncate(TEST_FILENAME, 0);
}

static int syscall_ftruncate() {

    int ret, fd;

    char buffer[] = "Hello testing";

    fd = open(TEST_FILENAME, O_CREAT | O_WRONLY, 0666);

    if (fd == -1) return 1;

    write(fd, buffer, sizeof(buffer));

    ret = ftruncate(fd, 0x20);

    close(fd);

    return ret;
}

int main(int argc, const char **argv) {
    size_t n;
    void (*syscall_table[3])(void) = {
        syscall_open,
        syscall_truncate,
        syscall_ftruncate,
    };

    n = (sizeof(syscall_table) / sizeof(syscall_table[0]));

    printf("\n\nThere are %ld syscalls wii be tested.\n\n", n);

    for (int i=0; i<n; i++) (*syscall_table[i])();

    return 0;
}
```

@chenhuitao 了解，以上是目前的想法

另外對應測試返回值判斷及 syscall name 的部分，我想在 py 中 hook syscall 來處理，您覺得恰當嗎?

**Comment by chenhuitao** [comment]
打印和判断应该都在对应的函数里，这样每个测试是独立的单元，在main中也就是直接调用。低耦合。我今天来写个示例或者模板吧。
恰当。py中hook syscall来处理，并且c语言中调用的syscall在独立运行时也有进行输出和判断返回值，可以和py中hook的结果比对。

**Comment by ucgJhe** [comment]
> 打印和判断应该都在对应的函数里，这样每个测试是独立的单元，在main中也就是直接调用。低耦合。我今天来写个示例或者模板吧。
> 恰当。py中hook syscall来处理，并且c语言中调用的syscall在独立运行时也有进行输出和判断返回值，可以和py中hook的结果比对。

please do

**Comment by chenhuitao** [comment]
```c
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>

#define TEST_FILENAME "test_syscall.txt"

static int syscall_open() {
    int fd;
    int flags;
    mode_t mode;

    flags = O_CREAT | O_WRONLY;
    mode = 0644;
    fd = open(TEST_FILENAME, flags, mode);
    printf("test: open(%s, 0x%x, 0%o) return %d.\n", TEST_FILENAME, flags,
            mode, fd);

    if (fd == -1) {
        fprintf(stderr, "%s at line %d error.", __func__, __LINE__);
        exit(1);
    }
    close(fd);

    return 0;
}

static int syscall_truncate() {
    int ret;
    int fd;
    int flags;
    mode_t mode;
    char buffer[] = "Hello testing";
    int len;
    off_t off;

    flags = O_CREAT | O_WRONLY;
    mode = 0644;
    fd = open(TEST_FILENAME, flags, mode);
    if (fd == -1) {
        fprintf(stderr, "%s at line %d error.", __func__, __LINE__);
        exit(1);
    }
    len = sizeof(buffer);
    ret = write(fd, buffer, len);
    if (ret != len) {
        fprintf(stderr, "%s at line %d error.", __func__, __LINE__);
        exit(1);
    }
    close(fd);

    off = 0;
    ret = truncate(TEST_FILENAME, off);
    printf("test: truncate(%s, 0x%x) return %d.\n", TEST_FILENAME, off, ret);
    if (ret == -1) {
        fprintf(stderr, "%s at line %d error.", __func__, __LINE__);
        exit(1);
    }

    /* check the file has been trucated or not. */
    /* stat(), check the st_size. */

    return 0;
}

int main(int argc, const char **argv) {

    syscall_open();

    syscall_truncate();

    return 0;
}
```

我设想的样子大概是这个样子。全部的功能都在自身的函数里来实现，各个函数之间也没有调用顺序等耦合。自身目标的，要测试的syscall函数的名称，参数和返回值应该输出。其他因准备上下文环境而调用的syscall或者其他函数，可以不做输出，但是应当做些必要的判断，确保目标syscall调用时的上下文环境与预期一致。如open中没有处理close，truncate中没有输出open，write等系统调用的参数和值。
异常时终止程序，便于各种集成CI来进行判断。本测试例内的内容在通常的环境中，应当全部成功。

@ucgJhe 如果您有更好的建议，也可以加进来。

**Comment by ucgJhe** [comment]
除了將 fprintf 改為 macro 外，其他我沒有想法
我會照這個模板推上相對應的 posix_syscall.c 與 testl_elf.py

**Comment by chenhuitao** [comment]
非常感谢。

**Comment by xwings** [comment]
謝謝 差不多可以merge了

**Comment by xwings** [comment]
hi,

the best is dont make another syscall in test. unless u want to test the ql.set_syscall function which is being tested.

**Comment by xwings** [comment]
It pas all the test now.
Appriciate if can update test_elf.py and remove the additional self fined syscall.

i will merge it once you update.

Thanks !

**Comment by ucgJhe** [comment]
> It pas all the test now.
> Appriciate if can update test_elf.py and remove the additional self fined syscall.
> 
> i will merge it once you update.
> 
> Thanks !

assertion failed because the certain file wasnt created as expected, and the self-define syscall was used for logging syscalls and make sure it functions well just like what we discussed before.

@xwings dont you think its necessary ?

**Comment by xwings** [comment]
its ok, we do not need there there for now.
technically it will crash the syscall fail. 

remove the customized syscall for now ? 

i think should be fine

**Comment by ucgJhe** [comment]
actually no, file not found wont crash the syscall_open, it is open_flags issue and i just fix it, if you uncomment the code everything should be work fine

just to make sure we dont double check the consequence of syscall in test_elf.py ?

**Comment by xwings** [comment]
i guess we dont have to. we are fine. i guess.

**Comment by xwings** [comment]
let me try for now

**Comment by xwings** [comment]
can you fix it for osx ?
https://travis-ci.com/qilingframework/qiling/jobs/269517253

or else we comment out for now

**Comment by ucgJhe** [comment]
failed because this (https://github.com/qilingframework/qiling/blob/master/qiling/os/utils.py#L353)
it will just return flags and dont care about arch

**Comment by xwings** [comment]
can you try to fix it?

**Comment by ucgJhe** [comment]
maybe need more arch here I guess https://github.com/qilingframework/qiling/pull/56/commits/92209ff066d4c986dde842f4a5d40d1f61f2e624

but I dont have any OSX devices to test .

**Comment by ucgJhe** [comment]
file not found because the open_flags didt mapping correctly

**Comment by ucgJhe** [comment]
`open(//test.file, 0x40a, 0x180) = -1` flags seem odd

0x40a = O_TRUNC | O_APPEND | O_RDWR

there is not O_CREAT

**Comment by ucgJhe** [comment]
I think i knew what happen `ql.platform == QL_MACOS` will make open_flags mapping from linux to mac , but it actually is Mch-O on mac

**Pull request merged**
