### PR TITLE
Make execve support scripts.

### PR DESCRIPTION
**Pull request by dark-lbp**
### Which kind of PR do you create?

- [x] This PR only contains minor fixes.
- [ ] This PR contains major feature update.
- [ ] This PR introduces a new function/api for Qiling Framework.

### Coding convention?

- [x] The new code conforms to Qiling Framework naming convention.
- [x] The imports are arranged properly.
- [x] Essential comments are added.
- [x] The reference of the new code is pointed out.

### Extra tests?

- [ ] No extra tests are needed for this PR.
- [ ] I have added enough tests for this PR.
- [x] Tests will be added after some discussion and review.

### Changelog?

- [ ] This PR doesn't need to update Changelog.
- [x] Changelog will be updated after some proper review.
- [ ] Changelog has been updated in my PR.

### Target branch?

- [x] The target branch is dev branch.

### One last thing

- [x] I have read the [contribution guide](https://docs.qiling.io/en/latest/contribution/)

-----

### CODE REVIEW

**Comment by xwings** [comment]
looks like you break the execve, try to fix it ?

**Comment by dark-lbp** [comment]
> looks like you break the execve, try to fix it ?

Working on it, Added file exist check before read.

**Comment by xwings** [comment]
i am still not very comfortable with the script execution in Qiling.

The problem here is, we only can execute the sell script. all others instrumentation is not working at all.

if we execve for the sake of execve, users can always run their custom execve ?

**Comment by dark-lbp** [comment]
> The problem here is, we only can execute the sell script. all others instrumentation is not working at all.

I read the interpreter from script first line, others script like `/bin/perl` or `/bin/python` might work too? 

> if we execve for the sake of execve, users can always run their custom execve ?

Make sense.

**Comment by dark-lbp** [comment]
I will open another pr about disable ql.debugger in execve and close this one.

**Pull request closed without merging**
