### PR TITLE
Start working on dynamically linked programs for QNX

### PR DESCRIPTION
**Pull request by danielmoos**
Currently Qiling fails to run dynamically linked QNX programs. At program start the loader sends a message of type 0x000 to request the path to the lib folder. These 2 commit add the message types of the System Manager and provide a basic implementation that returns the lib path /usr/lib for the system call sys_conf(GET, STRING, LIBPATH).

### Which kind of PR do you create?

- [ ] This PR only contains minor fixes.
- [x] This PR contains major feature update.
- [ ] This PR introduces a new function/api for Qiling Framework.

### Coding convention?

- [x] The new code conforms to Qiling Framework naming convention.
- [x] The imports are arranged properly.
- [x] Essential comments are added.
- [x] The reference of the new code is pointed out.

### Extra tests?

- [x] No extra tests are needed for this PR.
- [ ] I have added enough tests for this PR.
- [ ] Tests will be added after some discussion and review.

### Changelog?

- [ ] This PR doesn't need to update Changelog.
- [x] Changelog will be updated after some proper review.
- [ ] Changelog has been updated in my PR.

### Target branch?

- [x] The target branch is dev branch.

### One last thing

- [x] I have read the [contribution guide](https://docs.qiling.io/en/latest/contribution/)

-----

### CODE REVIEW

**Comment by xwings** [comment]
Hi,

Thanks for the PR.

Will you also be able to add a test case ?

**Comment by danielmoos** [comment]
> Will you also be able to add a test case ?

I'm sorry, the executable I'm using is from another department of the company and closed-source. Debugging it on the final product is rather complicated and time consuming, therefore we want to emulate it with Qiling. Sadly, I'm not allowed to share any proprietary software from the company.

**Comment by aquynh** [comment]
you can add a helloworld binary+source

**Comment by xwings** [comment]
@danielmoos u can write a dynamically link hellworld ?

**Comment by danielmoos** [comment]
> @danielmoos u can write a dynamically link hellworld ?

Yes, I can: [helloroot.zip](https://github.com/qilingframework/qiling/files/6798907/helloroot.zip)
A helloworld program is not that helpful because the interpreter ldqnx.so.2 is just a symlink to libc.so and Qiling already loads the interpreter. Therefore I attached a hello sqrt(2) program to use some functions provided by libm.so. There is one problem: I'm not sure if I'm allowed to share the QNX versions of libc.so and libm.so. And also I do not know if the license of QNX is compatible with the license of Qiling.
That said, you can find both libraries on GitHub in the [https://github.com/ezdevelop/qnx660/tree/master/target/qnx6/armle-v7/lib](QNX660 project). My rootfs has the structure
/usr/bin/helloroot
/usr/lib/ldqnx.so.2 -> libc.so.3
/usr/lib/libc.so -> libc.so.3
/usr/lib/libc.so.3
/usr/lib/libm.so -> libm.so.2
/usr/lib/libm.so.2
where -> denotes a symbolic link.

**Comment by madprogrammer** [comment]
@danielmoos according to the document http://support7.qnx.com/download/download/26724/TPLTL.v2.20.Sep30-14.pdf , libm.so.2 is licensed under BSD 4-clause license, and therefore can be added to the rootfs, provided that the copyright message is retained.

**Comment by xwings** [comment]
@danielmoos once you add in the test i will merge this PR.

thanks !

**Comment by danielmoos** [comment]
@madprogrammer thank you for this information! I have added a PR to the rootfs repo for the hello sqrt(2) program.

My local version of Qiling runs this program without any problems. Hopefully I find some time in the upcoming days to clean up my code and update this PR with my latest changes.

**Comment by danielmoos** [comment]
Besides the problem of the strange version of the QNX libc.so.3 in the rootfs repo mentioned in [PR #10](https://github.com/qilingframework/rootfs/pull/10), this code should work and be able to load dynamically linked libraries.

**Comment by xwings** [comment]
Hi,

my final few request

1. find a lib.so.3 that suitable for both cases?
2. add a example
3. add a test, in tests/test_qnx.py

**Comment by xwings** [comment]
I tried to run with your branch and it seems there are still some issue

image

**Comment by xwings** [comment]
i replaced the libc u suggested and it seems it work

**Comment by xwings** [comment]
I added both @madprogrammer and @danielmoos into the Contributors list :)

**Comment by danielmoos** [comment]
> I added both @madprogrammer and @danielmoos into the Contributors list :)

Thanks :)

I've used the weekend for some investigation and figured out, that the previous version of libc.so.3 in rootfs/arm_qnx/lib/ was taken from QNX 6.6. The current version of the libc.co.3 is now from QNX 6.5. But I do not know why the _CS_LIBPATH constant is defined as 200 in OpenQNX and QNX 6.5, but QNX 6.6 defines it as 12.
Well, we I guess we can ignore this problem until someone needs support for QNX 6.6.

**Comment by madprogrammer** [comment]
@danielmoos FYI I found that in QNX 6.6.0 _CS_LIBPATH is defined as 200, but 12 is another constant
`#define _CS_POSIXLY_CORRECT     12      /* Enable POSIX behaviour */`

This definition can be found in QNX SDK 6.6.0 `target/qnx6/usr/include/confname.h`

**Pull request merged**
