### PR TITLE
Fix mmap logic on MAP_FIXED

### PR DESCRIPTION
**Pull request by bet4it**
### Which kind of PR do you create?

- [x] This PR only contains minor fixes.
- [ ] This PR contains major feature update.
- [ ] This PR introduces a new function/api for Qiling Framework.

### Coding convention?

- [x] The new code conforms to Qiling Framework naming convention.
- [x] The imports are arranged properly.
- [x] Essential comments are added.
- [x] The reference of the new code is pointed out.

### Extra tests?

- [x] No extra tests are needed for this PR.
- [ ] I have added enough tests for this PR.
- [ ] Tests will be added after some discussion and review.

### Changelog?

- [ ] This PR doesn't need to update Changelog.
- [x] Changelog will be updated after some proper review.
- [ ] Changelog has been updated in my PR.

### Target branch?

- [x] The target branch is dev branch.

### One last thing

- [x] I have read the [contribution guide](https://docs.qiling.io/en/latest/contribution/)

-----
> If `addr` is NULL, then the kernel chooses the (page-aligned) address at which to create the mapping; this is the most portable method of creating a new mapping. **If `addr` is not NULL, then the kernel takes it as a hint about where to place the mapping;** on Linux, the kernel will pick a nearby page boundary (but always above or equal to the value specified by `/proc/sys/vm/mmap_min_addr`) and attempt to create the mapping there. **If another mapping already exists there, the kernel picks a new address that may or may not depend on the hint.** The address of the new mapping is returned as the result of the call.

If `addr` is not NULL, we need to map on this address even if `MAP_FIXED` is not set, except this address is already mapped.

### CODE REVIEW

**Comment by cla7aye15I4nd** [comment]
may be you can provide some test?

**Comment by bet4it** [comment]
I can't find any existing tests about `mmap`😅
And `mmap` is used in almost all programs, so we can test it base on the real usage of it.
I will send a PR of a realworld program which will trigger this bug lately. ( hope in this year😅 )

**Comment by xwings** [comment]
cool, waiting :)

**Comment by bet4it** [comment]
That will be another PR, hope this can be merged.

**Comment by xwings** [comment]
will you be able to solve the conflict?

**Comment by bet4it** [comment]
@xwings Done

**Pull request merged**
