### PR TITLE
fix dprint for bytes message

### PR DESCRIPTION
**Pull request by ucgJhe**
handle bytes message in dprint

### CODE REVIEW

**Comment by aquynh** [comment]
This looks ugly. Can we have self.debug() instead?

**Comment by ucgJhe** [comment]
sure, but how to tell which is nprint and dprint from context ?

**Comment by xwings** [comment]
@ucgJhe self.debug == QL_OUT_DUMP and QL_OUT_DEBUG is dprint, as usual.

nprint is normal print without debug or dump.

**Comment by ucgJhe** [comment]
you mean use self.debug to specify the level instead of self.output ?

I though he wants a self.debug function to do all the print out job

**Comment by xwings** [comment]
@aquynh what do you think.

**Comment by xwings** [comment]
i will take in this commit and we will plan in the next commit

**Pull request merged**
