### PR TITLE
Print a friendly name of the protocol in addition to its GUID.

### PR DESCRIPTION
**Pull request by assafcarlsbad**
This can help pinpoint what modules must be loaded to satisfy the target's dependencies, e.g.:
image

### Which kind of PR do you create?

- [x] This PR only contains minor fixes.
- [ ] This PR contains major feature update.
- [ ] This PR introduces a new function/api for Qiling Framework.

### Coding convention?

- [x] The new code conforms to Qiling Framework naming convention.
- [x] The imports are arranged properly.
- [x] Essential comments are added.
- [ ] The reference of the new code is pointed out.

### Extra tests?

- [x] No extra tests are needed for this PR.
- [ ] I have added enough tests for this PR.
- [ ] Tests will be added after some discussion and review.

### Changelog?

- [x] This PR doesn't need to update Changelog.
- [ ] Changelog will be updated after some proper review.
- [ ] Changelog has been updated in my PR.

### Target branch?

- [x] The target branch is dev branch.

### One last thing

- [x] I have read the [contribution guide](https://docs.qiling.io/en/latest/contribution/)

-----

### CODE REVIEW

**Comment by aquynh** [comment]
Why CSV, but not a proper Python code, so you do not have to process it at runtime?

**Comment by assafcarlsbad** [comment]
I took the CSV file directly from UEFITool: https://github.com/LongSoft/UEFITool/blob/new_engine/common/guids.csv
We can do some preprocessing on it to convert it into a proper Python dictionary. WDYT?

**Comment by xwings** [comment]
I think dict it is fine. Not much data.

**Comment by xwings** [comment]
Can you please fix the test error?

**Comment by assafcarlsbad** [comment]
Is it OK now?

**Comment by xwings** [comment]
Ok, Agree.

**Pull request merged**
