### PR TITLE
add syscall old_mmap for x86_32

### PR DESCRIPTION
**Pull request by ucgJhe**
according to the linux kernel this is only for ia32 compatibility.

### CODE REVIEW

**Comment by xwings** [comment]
if i not mistaken old_mmap works the same with mmap. maybe we just stick to mmap ?

**Comment by ucgJhe** [comment]
same implement but different interface, only happend when you run x86_32 binary calling syscall mmap directly from int 0x80 on arch x86_64.

**Comment by xwings** [comment]
i thin mips32 big endian also using old_mmap. can you check and comfirm ?  if not i mistaken  i mapped it to mmap. can you please also change it. 

also the old_mmap ql.nprint please change to old_mmap instate to the current mmap,

**Comment by xwings** [comment]
btw, i do keep a copy of mips32 EB binary in example/rootfs/mips32eb

**Comment by ucgJhe** [comment]
after test both mips32eb and mips32el use mmap.

**Comment by xwings** [comment]
cool. i will merge now

**Pull request merged**
