### PR TITLE
Bug Fixes in Windows Dll Initialization and New API Hooks

### PR DESCRIPTION
**Pull request by jhumble**
Changed uc.reg_write calls during dll param setup to properly pass in ints instead of bytes. Also added a few new api hooks.

### CODE REVIEW

**Comment by aquynh** [comment]
in the future, please separate unrelated changes into several pull reqs, so it is easier to merge them independently, thanks.

**Comment by xwings** [comment]
hi,

we do have ql.mem_write ?

**Comment by xwings** [comment]
There is a travis check fail. can you please check ?

**Comment by jhumble** [comment]
The failures are all in code that I didn't touch in these commits:

....
======================================================================
ERROR: test_elf_linux_arm64 (test_elf.ELFTest)                                                           
----------------------------------------------------------------------
Traceback (most recent call last):          
  File "/home/jhumble/tools/forked_qiling/tests/test_elf.py", line 130, in test_elf_linux_arm64
    ql.run()                                                
  File "../qiling/core.py", line 215, in run
    runner(self)                               
  File "../qiling/os/linux/arm64.py", line 99, in runner
    ql_arm64_enable_vfp(ql.uc)                    
  File "../qiling/os/linux/arm64.py", line 64, in ql_arm64_enable_vfp
    ARM64FP = uc.reg_read(UC_ARM64_REG_CPACR_EL1)                
NameError: name 'UC_ARM64_REG_CPACR_EL1' is not defined                                          
                                                                                                           
======================================================================
ERROR: test_elf_linux_arm64_static (test_elf.ELFTest)                 
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jhumble/tools/forked_qiling/tests/test_elf.py", line 136, in test_elf_linux_arm64_static
    ql.run()                               
  File "../qiling/core.py", line 215, in run
    runner(self)
  File "../qiling/os/linux/arm64.py", line 99, in runner
    ql_arm64_enable_vfp(ql.uc)
  File "../qiling/os/linux/arm64.py", line 64, in ql_arm64_enable_vfp
    ARM64FP = uc.reg_read(UC_ARM64_REG_CPACR_EL1)
NameError: name 'UC_ARM64_REG_CPACR_EL1' is not defined

======================================================================
ERROR: test_elf_linux_mips32el (test_elf.ELFTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jhumble/tools/forked_qiling/tests/test_elf.py", line 145, in test_elf_linux_mips32el
    ql.run()
  File "../qiling/core.py", line 215, in run
    runner(self)
  File "../qiling/os/linux/mips32el.py", line 268, in runner
    raise ql.internal_exception
  File "../qiling/core.py", line 23, in wrapper
    return func(*args, **kw)
  File "../qiling/core.py", line 285, in _callback
    callback(self, intno)
  File "../qiling/os/linux/mips32el.py", line 39, in hook_syscall
    raise QlErrorExecutionStop("[!] got interrupt 0x%x ???" %intno)
qiling.exception.QlErrorExecutionStop: [!] got interrupt 0x13 ???

======================================================================
ERROR: test_elf_linux_mips32el_posix_syscall (test_elf.ELFTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jhumble/tools/forked_qiling/tests/test_elf.py", line 224, in test_elf_linux_mips32el_posix_syscall
    ql.run()
  File "../qiling/core.py", line 215, in run
    runner(self)
  File "../qiling/os/linux/mips32el.py", line 268, in runner
    raise ql.internal_exception
  File "../qiling/core.py", line 23, in wrapper
    return func(*args, **kw)
  File "../qiling/core.py", line 285, in _callback
    callback(self, intno)
  File "../qiling/os/linux/mips32el.py", line 39, in hook_syscall
    raise QlErrorExecutionStop("[!] got interrupt 0x%x ???" %intno)
qiling.exception.QlErrorExecutionStop: [!] got interrupt 0x13 ???

======================================================================
ERROR: test_elf_linux_mips32el_static (test_elf.ELFTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "../qiling/os/linux/mips32el.py", line 56, in hook_syscall
    LINUX_SYSCALL_FUNC(ql, param0, param1, param2, param3, param4, param5)
  File "../qiling/os/linux/mips32el.py", line 183, in ql_syscall_mips32el_set_thread_area
    uc.reg_write(UC_MIPS_REG_CP0_CONFIG3, CONFIG3_ULR)
NameError: name 'UC_MIPS_REG_CP0_CONFIG3' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jhumble/tools/forked_qiling/tests/test_elf.py", line 154, in test_elf_linux_mips32el_static
    ql.run()
  File "../qiling/core.py", line 215, in run
    runner(self)
  File "../qiling/os/linux/mips32el.py", line 268, in runner
    raise ql.internal_exception
  File "../qiling/core.py", line 23, in wrapper
    return func(*args, **kw)
  File "../qiling/core.py", line 285, in _callback
    callback(self, intno)
  File "../qiling/os/linux/mips32el.py", line 65, in hook_syscall
    raise QlErrorSyscallError("[!] Syscall Implementation Error: %s" % (LINUX_SYSCALL_FUNC_NAME))
qiling.exception.QlErrorSyscallError: [!] Syscall Implementation Error: ql_syscall_mips32el_set_thread_area

----------------------------------------------------------------------
Ran 21 tests in 4.456s

FAILED (errors=5)

**Comment by xwings** [comment]
Hi, 

The build error is here. Not the one you show

https://travis-ci.com/qilingframework/qiling/jobs/275077817

**Comment by xwings** [comment]
we updated the qiling.os.windows .memory can you please update ?

**Comment by jhumble** [comment]
Seems to be testing fine on my local branch, but Travis is failing with the following error it seems:

The command "pip install 'capstone>=4.0.1' 'pefile>=2019.4.18' 'python-registry>=1.3.1' 'unicorn>=1.0.2rc1'" failed and exited with 1 during .
....
    -- Configuring incomplete, errors occurred!
    See also "C:/Users/travis/AppData/Local/Temp/pip-install-bzs8cuxd/capstone/src/build/CMakeFiles/CMakeOutput.log".
    See also "C:/Users/travis/AppData/Local/Temp/pip-install-bzs8cuxd/capstone/src/build/CMakeFiles/CMakeError.log".
    'nmake' is not recognized as an internal or external command,
    operable program or batch file.
    error: [Errno 2] No such file or directory: 'capstone.dll'

**Comment by xwings** [comment]
hi, 

there was a bug and we got it fixed. forcing a retest now

**Comment by xwings** [comment]
merge and thanks !

**Pull request merged**
