### PR TITLE
fix: fixing AttributeError in IDAPython

### PR DESCRIPTION
**Pull request by 0x79H**
fix: https://github.com/qilingframework/qiling/issues/1362

### Which kind of PR do you create?

- [x] This PR only contains minor fixes.
- [ ] This PR contains major feature update.
- [ ] This PR introduces a new function/api for Qiling Framework.

### Coding convention?

- [x] The new code conforms to Qiling Framework naming convention.
- [ ] The imports are arranged properly.
- [x] Essential comments are added.
- [ ] The reference of the new code is pointed out.

### Extra tests?

- [x] No extra tests are needed for this PR.
- [ ] I have added enough tests for this PR.
- [ ] Tests will be added after some discussion and review.

### Changelog?

- [ ] This PR doesn't need to update Changelog.
- [x] Changelog will be updated after some proper review.
- [ ] Changelog has been updated in my PR.

### Target branch?

- [x] The target branch is dev branch.

### One last thing

- [x] I have read the [contribution guide](https://docs.qiling.io/en/latest/contribution/)

-----

### CODE REVIEW

**Review by xwings — APPROVED** [review]

**Comment by xwings** [comment]
Thanks and welcome to Qiling Framework

**Comment by 0x79H** [comment]
i'm a noob🤦‍♂️

**Comment by xwings** [comment]
Hi, 

The code seems to break the test. I need to revert it. Will you be able to make another PR ?

**Comment by 0x79H** [comment]
> Hi,
> 
> The code seems to break the test. I need to revert it. Will you be able to make another PR ?

some contributor think "IDApython optimization should be in extentions". 
so i think we should move code to `qiling/extensions/idaplugin/qilingida.py`.

i will do it later.

**Comment by tats-gd** [comment]
I'm not sure if I really understand the problem. Should I just create a new PR?

**Comment by 0x79H** [comment]
> Hi,
> 
> The code seems to break the test. I need to revert it. Will you be able to make another PR ?

I think commit #1426  is unrelated to IDAPython.  And all checks passed.😂

**Pull request merged**
