### PR TITLE
hook for Sleep

### PR DESCRIPTION
**Pull request by re-fox**
Simple commit for hooking Sleep, in the case that there is malware that will check to make sure the Sleep command happened.  Uncomment the line to emulate the Windows Sleep in milliseconds.

### CODE REVIEW

**Comment by aquynh** [comment]
Cool, but we need a better way than this, as require to modify the code (uncommenting) is ugly.

**Comment by re-fox** [comment]
I agree with you.  Not an optimal solution.

In my opinion, it should be something that should be enabled by default giving the user an option to disable/enable via configuration item or argument passed.  Do you have thoughts on qiling having some global configuration items?

**Comment by aquynh** [comment]
Yes i would like to be able to optionally enable some features, like:

ql.function["sleep"] = true # false by default

Alternatively, we can also set our own customized functions, like:

ql.function["sleep"] = my_sleep

**Comment by xwings** [comment]
We implemented ql.set_syscall and ql.set_winapi. I will merge this and close. Since sleep doesn't really needed in Qiling Framework.

**Comment by xwings** [comment]
Thanks for the PR!

**Pull request merged**
