### PR TITLE
keep up qdb with Qdb and move README.md to docs.qiling.io

### PR DESCRIPTION
**Pull request by ucgJhe**
as title.

### CODE REVIEW

**Comment by aquynh** [comment]
Later this may be moved to the core, not in extensions/

**Comment by ucgJhe** [comment]
sure, any suggestion for that ? i can move it  within this PR.

**Comment by aquynh** [comment]
i am not sure. in my opinion, debugger/ should not be in extensions/, either.

**Comment by aquynh** [comment]
but it makes more sense if qdb/ is under debugger/ directory.

**Comment by xwings** [comment]
now my question is. we have ql.qdb == True and ql.debugger == True.

We should make ql.debugger = True (this will be qdb by default) , else gdb will be ql.debugger = gdb:127.0.0.1:9999

**Comment by xwings** [comment]
> but it makes more sense if qdb/ is under debugger/ directory.

and yes, to extentensions/debugger for now until we decide what to do

**Comment by aquynh** [comment]
> 
> 
> now my question is. we have ql.qdb == True and ql.debugger == True
> 
> We should make ql.debugger = True (this will be qdb by default) ,

if you set qdb to be the default debugger, this would break compatibility (since gdb used to be the default debugger)

**Comment by xwings** [comment]
i move qiling/extentions/debugger to qling/debugger, @ucgJhe u can move qdb there.

**Comment by xwings** [comment]
We should mak eql.debugger = "qdb" (this will be qdb, as suggested by quynh) ,

**Comment by aquynh** [comment]
you may change the filename examples/gdb.py to  examples/debugger.py

**Comment by xwings** [comment]
Looks Good and thanks!

**Pull request merged**
