### PR TITLE
Refactoring completed

### PR DESCRIPTION
**Pull request by elicn**
Changelog highlights:
- Cleaned and tidied up Qiling examples
- Revamped some of the examples, and added extra comments to make them clearer
- More typing info
- More import namespace cleanup
- Refactored files are put in place

### CODE REVIEW

**Comment by elicn** [comment]
Have no idea why that DOS test fails..
It works just fine over here (WSL2 with Python 3.8.5).

**Comment by wtdcode** [comment]
Will have a look.

**Comment by xwings** [comment]
I will merge, since we are still in "refactor" branch

**Comment by wtdcode** [comment]
Fixed in e92ede3fabc765937983e87cb2084a9e99611239, thanks to @chfl4gs

**Comment by elicn** [comment]
That is weird, considering that I did not reorganize the DOS folder..

**Pull request merged**
