### PR TITLE
try to use logging library for better logging

### PR DESCRIPTION
**Pull request by ucgJhe**
tested it on guest arch. x8664_linux, x86_linux (multithread included), mips32el on x8664_linux host, and partially rewrote print string to f-string.

may need more testing for other host arch.

### CODE REVIEW

**Comment by xwings** [comment]
can you please check, still some bug need to be fix. as per travis

**Comment by xwings** [comment]
Hi,

We can have make one of the test  in tests/test_elf with logs output. same goes with test_pe_nu

just pick and enable log_dir and log_split

**Comment by ucgJhe** [comment]
from here use logging library for both stdout and logging to disk file.

**Comment by ucgJhe** [comment]
@xwings gonna need more details for json and xml output (what should be printed, fields and value format etc.)to implement it.

**Comment by xwings** [comment]
json and xml will be another feature. we will make it another PR.

**Comment by xwings** [comment]
Thanks!

We will discuss in the Issue #30

**Pull request merged**
