### PR TITLE
Some performance improvements

### PR DESCRIPTION
**Pull request by elicn**
- QlCoreStructs: Resolve pack / unpack formats once instead of every time methods are called
- print_function: Reduce string copy / recreation by leveraging faster Python3 f-strings

### CODE REVIEW

**Comment by nullableVoidPtr** [comment]
Do you think there are some functions which would greatly benefit from the `functools.lru_cache` decorator?

**Comment by elicn** [comment]
Haven't seen any so far.
`print_function`, however, is not a good candidate for that since `lru_cache` caches results and `print_function` yields different results based on the emulated parameters and their values.

**Comment by xwings** [comment]
Thanks!

Will merge now.

**Comment by xwings** [comment]
i revert back to the old print_function. it did not pass the ci test

**Comment by elicn** [comment]
Couldn't understand what exactly went wrong on the Windows run.. I can see CI complaining it failed, I just don't see any assertion failure there. Could you please point out what's wrong?

**Comment by elicn** [comment]
Found and fixed the problem.
Resubmitted in a new PR.

**Pull request merged**
