### PR TITLE
UnboundLocalError, use before assignment, fixing of bytes.hex() calls

### PR DESCRIPTION
**Pull request by dannyquist**
### Which kind of PR do you create?

- [X] This PR only contains minor fixes.
- [ ] This PR contains major feature update.
- [ ] This PR introduces a new function/api for Qiling Framework.

### Coding convention?

- [X] The new code conforms to Qiling Framework naming convention.
- [ ] The imports are arranged properly.
- [ ] Essential comments are added.
- [ ] The reference of the new code is pointed out.

### Extra tests?

- [X] No extra tests are needed for this PR.
- [ ] I have added enough tests for this PR.
- [ ] Tests will be added after some discussion and review.

### Changelog?

- [X] This PR doesn't need to update Changelog.
- [ ] Changelog will be updated after some proper review.
- [ ] Changelog has been updated in my PR.

### Target branch?

- [X] The target branch is dev branch.

### One last thing

- [X] I have read the [contribution guide](https://docs.qiling.io/en/latest/contribution/)

-----

### CODE REVIEW

**Comment by elicn** [comment]
Why removing the space parameter from the `hex` represenation?
It's not a bug, it is there to put a space between hex bytes, which makes long hex strings more readable (e.g. `'68 65 6c 6c 6f 20 77 6f 72 6c 64'`)

**Comment by dannyquist** [comment]
Any chance you could DM me on twitter? I'm @openmalware there

**Comment by cq674350529** [comment]
@elicn In `python 3.6`, call `hex()` with additional paramter will cause error.

```python
Python 3.6.9 (default, Jan 26 2021, 15:33:00) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.14.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: tmp = b"00112233"                                                          

In [2]: tmp.hex()                                                                  
Out[2]: '3030313132323333'

In [3]: tmp.hex("")                                                                
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-b882162dbcb0> in <module>
----> 1 tmp.hex("")

TypeError: hex() takes no arguments (1 given)
```

**Comment by elicn** [comment]
> @elicn In `python 3.6`, call `hex()` with additional paramter will cause error.

Yes, the reason for that is indeed an older version of Python. We continued our conversation over DM so it's not recorded here, but this is what I told @dannyquist. From looking at the project's test suits it looks like the miminal Python version is 3.8, so passing an argument to `hex` should be supported.

@xwings, perhaps it would be helpful to issue a runtime warning based on the Python version (that is, if the running version is below the one supported, issue a warning to the user)

**Comment by cq674350529** [comment]
Yes, currently there is no explicit python3 version requirement. What I can find in the doc is:
> For this installation guide, Ubuntu desktop 18.04.3 LTS 64bit is the base example (Qiling Framework works in other Linux distributions that run Python 3.5 and above

I'm running with Ubuntu 18.04.6, and the default python3 version is `python 3.6`. At least, most of feaure works with `python 3.6`.

**Comment by elicn** [comment]
Sadly, the documentation is often outdated.. Practically Ubuntu 20.4 / Python 3.8 are used.

**Pull request closed without merging**
