### PR TITLE
Revise the method of syscall_nr acquisition in the ARMOABI mode

### PR DESCRIPTION
**Pull request by rootkiter**

### CODE REVIEW

**Comment by rootkiter** [comment]
https://github.com/unicorn-engine/unicorn/issues/1137

**Comment by wtdcode** [comment]
Seems strange. I need to investigate it in details. Could you post a test binary?

**Comment by rootkiter** [comment]
mirai arm o3
This is a sample of MIRAI that I compiled. AND It is  ARMOABI.

**Comment by xwings** [comment]
Hi,

will you be able to add in as a test case ?

**Comment by rootkiter** [comment]
> Hi,
> 
> will you be able to add in as a test case ?

Who can help me finish the rest of the work? I don't know how to continue now

**Comment by rootkiter** [comment]
> Hi,
> 
> will you be able to add in as a test case ?

It was finished last week.

**Comment by xwings** [comment]
Please include the src too

**Comment by rootkiter** [comment]
> Please include the src too

It's the original code in the project. 

https://github.com/qilingframework/qiling/blob/1f1e9bc756e59a0bfc112d32735f8882b1afc165/examples/src/linux/posix_syscall.c

https://github.com/qilingframework/rootfs/pull/6#issuecomment-873019316

**Comment by xwings** [comment]
cool, thanks

**Comment by xwings** [comment]
the test is not being executed ? it should be in the test folder. not example. and make sure in test_elf.sh

**Comment by rootkiter** [comment]
Why cann't find the binary.

**Comment by rootkiter** [comment]
> Why cann't find the binary.

image

**Comment by xwings** [comment]
can you please resolve the conflict ?

**Pull request closed without merging**
