### PR TITLE
Verbose posix syscall error logging

### PR DESCRIPTION
**Pull request by PeterStolz**
The debug logging of syscall return values just returns the actual number instead of the error name like -0xa instead of SIGCHILD.   
In this version the number is returned and if the error code is known it is printed aswell.
`ioctl() = -0x1` becomes    
`ioctl() = -0x1|EPERM` which saves a lot of time understanding what went wrong.
The actual error codes come from the [official linux kernel repository](https://github.com/torvalds/linux.git) from the files ["tools/include/uapi/asm-generic/errno-base.h"](https://github.com/torvalds/linux/blob/master/tools/include/uapi/asm-generic/errno-base.h) and ["tools/include/uapi/asm-generic/errno.h"](https://github.com/torvalds/linux/blob/master/tools/include/uapi/asm-generic/errno.h) and were added to posix/const.py as a dict.

I also changed SIGCHILD fom -10 to 10, which fixes a bug I intruduced in [my last PR](https://github.com/qilingframework/qiling/pull/600) where the syscall wait returns 10 instead of -10 upon the SIGCHILD error.

### Which kind of PR do you create?

- [ ] This PR only contains minor fixes.
- [ ] This PR contains major feature update.
- [ ] This PR introduces a new function/api for Qiling Framework.

### Coding convention?

- [X] The new code conforms to Qiling Framework naming convention.
- [X] The imports are arranged properly.
- [X] Essential comments are added.
- [X] The reference of the new code is pointed out.

### Extra tests?

- [X] No extra tests are needed for this PR.
- [ ] I have added enough tests for this PR.
- [ ] Tests will be added after some discussion and review.

### Changelog?

- [X] This PR doesn't need to update Changelog.
- [ ] Changelog will be updated after some proper review.
- [ ] Changelog has been updated in my PR.

### Target branch?

- [X] The target branch is dev branch.

### One last thing

- [X] I have read the [contribution guide](https://docs.qiling.io/en/latest/contribution/)

-----

### CODE REVIEW

**Comment by aquynh** [comment]
"|" can be misunderstood as logical OR. Can you come up with something else?

**Comment by PeterStolz** [comment]
Would ":" do the job?

**Comment by xwings** [comment]
I suggest we go for ()  as in ioctl() = -0x1(EPERM)

**Comment by PeterStolz** [comment]
Ok. It looks better now.

**Comment by xwings** [comment]
Thanks!

Merged.

**Pull request merged**
