### PR TITLE
verbose level for different debug output

### PR DESCRIPTION
**Pull request by ucgJhe**
merge this for different debug output
0 for normal debug
1 for display constant symbol , read/write/send/recv content

### CODE REVIEW

**Comment by xwings** [comment]
Hi,

You might want to take look for Windows too ?

**Comment by ucgJhe** [comment]
will see what i can do

**Comment by xwings** [comment]
THANKS!

but let me merge the big PR first. and we'll see how we move.

**Comment by xwings** [comment]
ok, as expected. we got some conflict.

**Comment by xwings** [comment]
Prefect ! Thanks !

**Pull request merged**
