### PR TITLE
Support EFI_FIRMWARE_VOLUME2_PROTOCOL.

### PR DESCRIPTION
**Pull request by assafcarlsbad**
Some UEFI drivers such as `PcdDxe` on my system uses the `EFI_FIRMWARE_VOLUME2_PROTOCOL` in order to read specific sections from the BIOS image. This PR is a preliminary attempt to implement this protocol on top of the excellent [uefi-firmware-parser](https://github.com/theopolis/uefi-firmware-parser) library.

### CODE REVIEW

**Comment by xwings** [comment]
looks like this PR  affect code coverage ? will you be able to fix it ?

**Comment by assafcarlsbad** [comment]
On it.

**Comment by xwings** [comment]
If we did not use too many code from uefi_firmware , can we write the code on our own ?

**Comment by assafcarlsbad** [comment]
I'm afraid `uefi_firmware` does a lot of low-level parsing under the hood. We only need it to support fuzzing of entire firmware volumes rather than standalone modules. If this use case is too specialized (and I can agree with such statement), than we can leave it outside Qiling altogether and make it a part of the fuzzer instead.

**Comment by xwings** [comment]
Ok.

There are few reasons. Mainly i want to keep installation module as less as possible unless is required for the core.

Any more options ?

**Pull request closed without merging**
