### PR TITLE
netgear_6220_mips32el_linux plus

### PR DESCRIPTION
**Pull request by zi0Black**
This file's intension is to provide some examples of more advanced operation done with qiling on this binary.
Added:
File -> netgear_6220_mips32el_linux_plus.py
Custom api -> bind -> read & decode C struct from memory

Improved:
N/A

Fixed:
N/A

### CODE REVIEW

**Comment by xwings** [comment]
We just need a copy of R6220. My suggestion is either:

1. Use another firmware for example, i guess all the netgear are pretty much the same
2. Merge this into the current R6220, we dont need two 6220

Also, if you can blog this example it will be really awesome!

**Comment by xwings** [comment]
Also, Welcome to the community!

**Comment by zi0Black** [comment]
> We just need a copy of R6220. My suggestion is either:
> 
> 1. Use another firmware for example, i guess all the netgear are pretty much the same
> 2. Merge this into the current R6220, we dont need two 6220
> 
> Also, if you can blog this example it will be really awesome!

I think I will merge with the existing one! (I thought about creating a new file to keep the first one as simple as possible and have another one more complex e detailed were to keep posting more complex tricks). 

I don't have a blog :/

**Comment by xwings** [comment]
Ok, merge the current one will be perfect.

You can always write in https://docs.qiling.io  , the github repo in https://github.com/qilingframework/rtfd.io

**Comment by zi0Black** [comment]
> Ok, merge the current one will be perfect.
> 
> You can always make your own blog with github pages. https://pages.github.com/

ACK.

**Pull request closed without merging**
