### PR TITLE
Fix broken QNX support

### PR DESCRIPTION
**Pull request by madprogrammer**
### Which kind of PR do you create?

- [X] This PR only contains minor fixes.
- [ ] This PR contains major feature update.
- [ ] This PR introduces a new function/api for Qiling Framework.

### Coding convention?

- [X] The new code conforms to Qiling Framework naming convention.
- [X] The imports are arranged properly.
- [X] Essential comments are added.
- [X] The reference of the new code is pointed out.

### Extra tests?

- [X] No extra tests are needed for this PR.
- [ ] I have added enough tests for this PR.
- [ ] Tests will be added after some discussion and review.

### Changelog?

- [X] This PR doesn't need to update Changelog.
- [ ] Changelog will be updated after some proper review.
- [ ] Changelog has been updated in my PR.

### Target branch?

- [X] The target branch is dev branch.

### One last thing

- [X] I have read the [contribution guide](https://docs.qiling.io/en/latest/contribution/)

-----
QNX support was broken after some changes in `mman.py`. Also I've moved `syspage.bin` helper file from `examples` into the `os/qnx`, similar to how `guids.csv` is searched for in UEFI OS, because `syspage.bin` search was also broken when trying to run provided `hello_arm_qnx.py` or QNX fuzzing example.

### CODE REVIEW

**Comment by xwings** [comment]
please change to dev branch :)

**Comment by xwings** [comment]
syspage.bin should be in rootfs ?

**Comment by madprogrammer** [comment]
`syspage.bin` is a snapshot of an in-memory structure normally filled by the startup file (e.g. bootloader), before the QNX kernel starts to execute. I could place it in rootfs if you think it belongs there.

**Comment by xwings** [comment]
yes. put it there. it should be in the root.

**Comment by xwings** [comment]
Thanks.

merge for now

**Pull request merged**
