### PR TITLE
Add windows_sdk json file

### PR DESCRIPTION
**Pull request by kabeor**
{
   " function_name": [
         {
              "name": xxxx,
              "type": "int"
         }
    ]
}

### CODE REVIEW

**Comment by klks** [comment]
can the json files be put into a folder, maybe call it definitions of defs. the parser script for this can then live in the windows_sdk folder. we should also branch this into a feature and once its complete, merge it back into dev.

**Comment by kabeor** [comment]
Totally understand. I'm trying to make json file more complete and let fncc.py use it.

**Comment by xwings** [comment]
new base now

**Comment by xwings** [comment]
i will merge now and lets work on the CC

**Pull request merged**
