### PR TITLE
fixes for gdb debugserver

### PR DESCRIPTION
**Pull request by D3Smind**
fixes for the problems described in #254

### CODE REVIEW

**Comment by xwings** [comment]
The problem is,

i tried with gdb and ida pro it seems to be working fine withe the exe. can u do a pull and check again ?

**Comment by xwings** [comment]
But you are right with the Manifest :)

**Comment by xwings** [comment]
image

should be working

**Comment by xwings** [comment]
i make the entry_point standardized in gdb so we dont have to be confuse. can you try and and update the conflict. 

i will merge this PR after u solve the conflict

**Comment by D3Smind** [comment]
that is the far better solution :+1: 

thx for the help and the great emulator

**Comment by xwings** [comment]
Once again,

Welcome to the group. Hope to see more PR !

**Pull request merged**
