### PR TITLE
Add x86_64 debug support

### PR DESCRIPTION
**Pull request by HackingFrogWithSunglasses**
As per https://github.com/qilingframework/qiling/pull/1217 - here is the x86_64 Qdb support

### Which kind of PR do you create?

- [ ] This PR only contains minor fixes.
- [ ] This PR contains major feature update.
- [*] This PR introduces a new function/api for Qiling Framework.

### Coding convention?

- [*] The new code conforms to Qiling Framework naming convention.
- [*] The imports are arranged properly.
- [*] Essential comments are added.
- [ ] The reference of the new code is pointed out.

### Extra tests?

- [ ] No extra tests are needed for this PR.
- [ ] I have added enough tests for this PR.
- [*] Tests will be added after some discussion and review.

### Changelog?

- [ ] This PR doesn't need to update Changelog.
- [ ] Changelog will be updated after some proper review.
- [*] Changelog has been updated in my PR.

### Target branch?

- [*] The target branch is dev branch.

### One last thing

- [*] I have read the [contribution guide](https://docs.qiling.io/en/latest/contribution/)

-----

### CODE REVIEW

**Comment by elicn** [comment]
@ucgJhe - you are welcome to comment.

**Comment by ucgJhe** [comment]
@HackingFrogWithSunglasses Thanks for your contribution, add some tests for Qdb will make this PR even better.

**Comment by HackingFrogWithSunglasses** [comment]
> 

Hey,

Thanks for your positive feedback, I really appreciate it.

Unfortunately, I simply don't have the time to refine this PR to the way in which you may like. I am also not the best placed person to do this, as I am not a developer. I simply decided to upstream these changes because I felt like other might want them.

You are absolutely welcome to adapt the PR and use it, or not. I am fine with either way :)

**Comment by xwings** [comment]
Hey, welcome to Qiling.

I will merge as per advice from @ucgJhe, thank you!

**Review by xwings — APPROVED** [review]

**Review by kabeor — APPROVED** [review]

**Pull request merged**
