### PR TITLE
add x86_fetch_urandom binary

### PR DESCRIPTION
**Pull request by ucgJhe**
silly me, totally forgot to upload the binary for fetch_urandom

### CODE REVIEW

**Comment by xwings** [comment]
lol. cool. we got the source code ? and maybe add in the tests too ?

**Comment by ucgJhe** [comment]
we did have it here https://github.com/qilingframework/qiling/blob/dev/examples/src/linux/fetch_urandom.c

**Comment by xwings** [comment]
Do u want to put it in test too ?

**Comment by ucgJhe** [comment]
just did

**Comment by xwings** [comment]
cool

**Pull request merged**
