### PR TITLE
add new feature: fs_mapper hijacking

### PR DESCRIPTION
**Pull request by ucgJhe**
add new feature fs_mapper hijacking and corresponding example

### CODE REVIEW

**Comment by w1tcher** [comment]
This is a good idea. But I think add_fs_mapper should pass in a class, not an instance. 
https://github.com/qilingframework/qiling/pull/346/commits/1e500000df025b4f232917db59ae35057f04906a#diff-24f7844cea3bdc52061cf711e422fedbR31
We can change this here.
```python
        elif not isinstance(open_path, str):
            return open_path()
```

**Comment by ucgJhe** [comment]
I did have a nvram example for this feature, and it does need object to handle read/write operation and so on , thats why I use instance but not class here.

**Comment by ucgJhe** [comment]
I did have a example for nvram , by that case read/write operation will be handled and I need instance to keep the result.

**Comment by w1tcher** [comment]
OK

**Comment by w1tcher** [comment]
OK, Thanks.

**Pull request merged**
