### PR TITLE
Change deprecated interfaces of IDA

### PR DESCRIPTION
**Pull request by machinewu**
### Which kind of PR do you create?

- [x] This PR only contains minor fixes.
- [ ] This PR contains major feature update.
- [ ] This PR introduces a new function/api for Qiling Framework.

### Coding convention?

- [ ] The new code conforms to Qiling Framework naming convention.
- [ ] The imports are arranged properly.
- [ ] Essential comments are added.
- [ ] The reference of the new code is pointed out.

### Extra tests?

- [ ] No extra tests are needed for this PR.
- [ ] I have added enough tests for this PR.
- [ ] Tests will be added after some discussion and review.

### Changelog?

- [ ] This PR doesn't need to update Changelog.
- [ ] Changelog will be updated after some proper review.
- [ ] Changelog has been updated in my PR.

### Target branch?

- [x] The target branch is dev branch.

### One last thing

- [x] I have read the [contribution guide](https://docs.qiling.io/en/latest/contribution/)

-----

Just recreate a PR for part of #1095. 

Some minor fixes:
1. According to [IDA's IDAPython official documentation](https://hex-rays.com/products/ida/support/ida74_idapython_no_bc695_porting_guide/), some of the old methods have changed names for a long time. In IDA v7.7, some methods are no longer available. Follow the documentation to change the method in `qiling/extensions/idaplugin/qilingida.py`.

### CODE REVIEW

**Review by xwings — APPROVED** [review]

**Comment by kabeor** [comment]
@machinewu Hi, is your code still works well on 7.6 and earlier version?

**Comment by machinewu** [comment]
Maybe. I remember that I tested it before on 7.2 and it worked. I use 7.7 can work.

**Comment by xwings** [comment]
> Maybe. I remember that I tested it before on 7.2 and it worked. I use 7.7 can work.

So, this code is specific for 7.7 and above ?
If we take in this changes, only work for 7.7 ?

If this so, we need to do a version check

**Comment by machinewu** [comment]
I just test 7.2 & 7.7

**Comment by xwings** [comment]
> I just test 7.2 & 7.7

U mean this code works on both ?

**Comment by machinewu** [comment]
> > I just test 7.2 & 7.7
> 
> U mean this code works on both ?

yes

**Review by kabeor — APPROVED** [review]

**Comment by kabeor** [comment]
Thank you for your contribution! Merged.

**Pull request merged**
