### PR TITLE
Add implementations for GetSystemTime, FindFirstFile, WIN32_FIND_DATA, and FILE_ATTRIBUTES

### PR DESCRIPTION
**Pull request by lucroida**
References:
- https://docs.microsoft.com/en-us/windows/win32/api/minwinbase/ns-minwinbase-win32_find_dataa
- https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-findfirstfilea
- https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-findfirstfileexac
- https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-findfirstfileexa
- https://docs.microsoft.com/en-us/windows/win32/fileio/file-attribute-constants

### CODE REVIEW

**Comment by xwings** [comment]
Hi,

Do you have test binary for all these APIs?

**Comment by lucroida** [comment]
No. I will write one and add it to the PR 👍

**Comment by xwings** [comment]
Thanks, i will merge after your sample

**Comment by xwings** [comment]
Hi,

I have tested and it seems ok. I will merge it now and feel free to make another PR for the test

**Pull request merged**
