### PR TITLE
Added fiber manager, supporting fiber apis and bunch of other api hooks

### PR DESCRIPTION
**Pull request by jhumble**
Added fiber manager, supporting fiber apis and bunch of other api hooks.

### CODE REVIEW

**Comment by xwings** [comment]
Hi, 

As usual, do we have a test case ? maybe you can add it in test/test_pe_nu.py

**Comment by jhumble** [comment]
This should all work fine, but it's not currently actually running the callback functions

As indicated in the big block comment in FiberManager.free(), I'm not sure how to actually have unicorn emulate the callback function. I can set up the callback parameters and return address, but as soon as the api hook for FlsFree finishes up and execution moves back to fncc, the wrapper code squashes any changes I've made to EIP/RIP by overwriting them with the return address from FlsFree.

Is there a clean way to actually accomplish this?

**Comment by xwings** [comment]
Let the "PE Department" comment, @Dliv3

**Comment by xwings** [comment]
@jhumble we still need some simple method to test the code. 

Once a wise man said, untested code is not a proven code. I quote from Dr. @aquynh

**Comment by jhumble** [comment]
I added Fls.exe and a quick test (Similar to the others) in test_pe_nu.py. Did you want me to add something else also?

**Comment by xwings** [comment]
Thanks !!!! we will test and merge ASAP.

**Comment by Dliv3** [comment]
Thanks! Merged 😀

**Pull request merged**
