### PR TITLE
update return register accordingly for all arch

### PR DESCRIPTION
**Pull request by ucgJhe**
update return register accordingly, so setReturnAddress could work as expected.

### CODE REVIEW

**Comment by elicn** [comment]
I am wondering why these haven't failed so far.. @ucgJhe, did you encounter any failures that brought you to fix these?

Also, would appreciate another pair of eyes that are more familiar with those arch that I do.
@wtdcode, what do you think?

**Comment by ucgJhe** [comment]
> I am wondering why these haven't failed so far.. @ucgJhe, did you encounter any failures that brought you to fix these?
> 
> Also, would appreciate another pair of eyes that are more familiar with those arch that I do. @wtdcode, what do you think?

Basically, I've been working on improving function call feature and happened to found this is not in the right place.

**Comment by xwings** [comment]
> > I am wondering why these haven't failed so far.. @ucgJhe, did you encounter any failures that brought you to fix these?
> > Also, would appreciate another pair of eyes that are more familiar with those arch that I do. @wtdcode, what do you think?
> 
> Basically, I've been working on improving function call feature and happened to found this is not in the right place.

interesting. i think you should start to add in some small unit test. i remember u told me the test run too long. but again, bad test it ways better better then no test.

**Review by elicn — APPROVED** [review]

**Comment by wtdcode** [comment]
> I am wondering why these haven't failed so far.. @ucgJhe, did you encounter any failures that brought you to fix these?
> 
> Also, would appreciate another pair of eyes that are more familiar with those arch that I do. @wtdcode, what do you think?

The comment seems left by me. IIRC, the reason behind the comment is that, depending on the context, the return address _may_ be on stack, say interrupt handlers. Though in most cases for userland code, LR is used instead.

**Review by xwings — APPROVED** [review]

**Pull request merged**
